# Generated by Django 2.1.3 on 2019-02-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='compliance_version',
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='compliance',
            field=models.ForeignKey(default=1, help_text='Compliance.  May have multiple versions', on_delete=django.db.models.deletion.PROTECT, related_name='compliance', to='risk.Compliance'),
        ),
    ]
