# Generated by Django 2.1.3 on 2018-11-04 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCategoryControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorycontrol_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorycontrol_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorycontrol_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control: Control Categories',
            },
        ),
        migrations.RemoveField(
            model_name='controlcategoryprotection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryprotection',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryprotection',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryprotection',
            name='id_control',
        ),
        migrations.RemoveField(
            model_name='controlcategoryprotection',
            name='id_controlcategory',
        ),
        migrations.RemoveField(
            model_name='controlcategoryprotection',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='control',
            name='control_protection',
        ),
        migrations.DeleteModel(
            name='ControlCategoryProtection',
        ),
        migrations.AddField(
            model_name='controlcategorycontrol',
            name='id_control',
            field=models.ForeignKey(help_text='The control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlcategory_control', to='risk.Control'),
        ),
        migrations.AddField(
            model_name='controlcategorycontrol',
            name='id_controlcategory',
            field=models.ForeignKey(help_text='Category of control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_controlcategory', to='risk.ControlCategory'),
        ),
        migrations.AddField(
            model_name='controlcategorycontrol',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorycontrol_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='categories',
            field=models.ManyToManyField(help_text='The protection categories that the control provides', related_name='controlcategory_controlcategor', through='risk.ControlCategoryControl', to='risk.ControlCategory'),
        ),
    ]
