# Generated by Django 2.0.5 on 2018-05-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='url',
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_main',
            field=models.URLField(blank=True, help_text='Vendors main website'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_product',
            field=models.URLField(blank=True, help_text='Vendors products website'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_service',
            field=models.URLField(blank=True, help_text='Vendors services website'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_support',
            field=models.URLField(blank=True, help_text='Vendors support website'),
        ),
    ]
