# Generated by Django 2.1.3 on 2019-02-27 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20190226_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryComplianceRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('is_test', models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_activated', models.DateTimeField(editable=False, help_text='Timestamp the field was last activated')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('activated_by', models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliancerequirement_related_activated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliancerequirement_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliancerequirement_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliancerequirement_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('id_compliance_requirement', models.ForeignKey(help_text='The compliance requirement or regulation associated with the entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrycompliancerequirement', to='risk.ComplianceRequirement')),
            ],
            options={
                'verbose_name_plural': 'Entry Compliance Requirements',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='compliances',
            field=models.ManyToManyField(help_text='Specifies what requirements are associated with the entry', related_name='EntryCompliances', through='risk.EntryCompliance', to='risk.Compliance'),
        ),
        migrations.AddField(
            model_name='entrycompliancerequirement',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrycompliancerequirement', to='risk.Entry'),
        ),
        migrations.AddField(
            model_name='entrycompliancerequirement',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliancerequirement_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='compliance_requirements',
            field=models.ManyToManyField(help_text='Specifies what requirements are associated with the entry', related_name='EntryComplianceRequirements', through='risk.EntryComplianceRequirement', to='risk.ComplianceRequirement'),
        ),
    ]
