# Generated by Django 2.0.5 on 2018-10-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20181024_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeunit',
            name='date_created',
        ),
    ]
