# Generated by Django 2.1.3 on 2019-08-06 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_entryancillary_cadence'),
    ]

    operations = [
        migrations.AddField(
            model_name='severitycategory',
            name='measure',
            field=models.CharField(default=django.utils.timezone.now, help_text='Measurement of the severity', max_length=45),
            preserve_default=False,
        ),
    ]
