# Generated by Django 2.1.3 on 2018-11-04 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20181104_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCategoryNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('description', models.TextField(help_text='Description of the how the control would operate at the selected level')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorynotification_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorynotification_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorynotification_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Category: Notification Types',
            },
        ),
        migrations.CreateModel(
            name='ControlNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the field', null=True)),
                ('sort_order', models.IntegerField(blank=True, help_text='Sort order that the operational level should be in for form selection', null=True)),
                ('company', models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlnotification_related_company', to='risk.Company')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlnotification_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlnotification_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlnotification_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlnotification_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Notifications',
            },
        ),
        migrations.RemoveField(
            model_name='controlcategoryoperation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryoperation',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryoperation',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryoperation',
            name='id_controlcategory',
        ),
        migrations.RemoveField(
            model_name='controlcategoryoperation',
            name='id_controloperation',
        ),
        migrations.RemoveField(
            model_name='controlcategoryoperation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='available_operation',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='operation',
        ),
        migrations.DeleteModel(
            name='ControlCategoryOperation',
        ),
        migrations.DeleteModel(
            name='ControlOperation',
        ),
        migrations.AddField(
            model_name='controlcategorynotification',
            name='id_controlcategory',
            field=models.ForeignKey(help_text='Category of control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_control_operation', to='risk.ControlCategory'),
        ),
        migrations.AddField(
            model_name='controlcategorynotification',
            name='id_controlnotification',
            field=models.ForeignKey(help_text='Type of notification response the control provides.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_control_category', to='risk.ControlNotification'),
        ),
        migrations.AddField(
            model_name='controlcategorynotification',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorynotification_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='available_notification',
            field=models.ManyToManyField(help_text='The level at which the control category operates', related_name='ControlNotificationLevel', through='risk.ControlCategoryNotification', to='risk.ControlNotification'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='notification',
            field=models.ForeignKey(blank=True, help_text='The notification ability associated to the control entered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_controlentry', to='risk.ControlNotification'),
        ),
    ]
