# Generated by Django 2.1.3 on 2018-11-26 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20181122_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryurl',
            name='recommended_by',
            field=models.ForeignKey(blank=True, help_text='User that recommended the URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='recommended_notes',
            field=models.TextField(blank=True, help_text='Notes on why the url was recommended reading for other RLB users', null=True),
        ),
    ]
