# Generated by Django 2.0.5 on 2018-05-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_remove_companycontact_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='vendor',
        ),
    ]
