# Generated by Django 2.1.3 on 2018-11-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20181104_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlnotification',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='controlnotification',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlnotification',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlnotification',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
    ]
