# Generated by Django 2.1.3 on 2019-02-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20190227_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryurl',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryurl', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the entry', null=True),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='name',
            field=models.TextField(blank=True, help_text='name of the entry', max_length=225, null=True),
        ),
    ]
