# Generated by Django 2.1.3 on 2018-11-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_auto_20181126_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryurl',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes on why the url was selected for the entry', null=True),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='url',
            field=models.URLField(help_text='URL used to support detail of the entry', max_length=512),
        ),
    ]
