# Generated by Django 2.1.3 on 2019-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_severitycategory_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcategory',
            name='roi_detail',
            field=models.TextField(blank=True, help_text='How is the ROI defined for the control category.', null=True),
        ),
    ]
