# Generated by Django 2.1.3 on 2018-11-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20181104_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliance',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterField(
            model_name='controlnotification',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
    ]
