# Generated by Django 2.0.5 on 2018-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_remove_timeunit_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was created', null=True),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
    ]
