# Generated by Django 2.1.3 on 2019-03-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20190228_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryurl',
            name='id_entry',
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='name',
            field=models.CharField(blank=True, help_text='Summary of the %(class)s', max_length=225, null=True),
        ),
    ]
