# Generated by Django 2.0.5 on 2018-05-27 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_remove_control_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='If vendor is chosen for contact type, which vendor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendorcontact', to='risk.Vendor'),
        ),
        migrations.AddField(
            model_name='control',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor that produces the control ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controldetail', to='risk.Vendor'),
        ),
    ]
