# Generated by Django 2.0.5 on 2018-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20181024_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='annual_units',
            field=models.IntegerField(blank=True, help_text='Number of units in a year', max_length=8, null=True),
        ),
    ]
