# Generated by Django 2.1.3 on 2018-11-05 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20181104_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCategoryCIATriad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('context', models.TextField(blank=True, help_text='Context regarding the CIA triad')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryciatriad_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryciatriad_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryciatriad_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('id_ciatriad', models.ForeignKey(help_text='The CIA Triad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlcategory_cia', to='risk.CIATriad')),
                ('id_controlcategory', models.ForeignKey(help_text='The control category the associated with the CIA Triad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cia_controlcategory', to='risk.ControlCategory')),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryciatriad_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Category: CIA Triad',
            },
        ),
        migrations.AlterModelOptions(
            name='compliance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='controlnotification',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Control Notifications'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='cia_triad',
            field=models.ManyToManyField(help_text='Specifies what portion of the triad is associated to the control category', related_name='ControlCategoryCIATriads', through='risk.ControlCategoryCIATriad', to='risk.CIATriad'),
        ),
    ]
