# Generated by Django 2.1.3 on 2018-12-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20181201_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlcategory',
            old_name='available_notification',
            new_name='control_response',
        ),
        migrations.RenameField(
            model_name='entrycompanycontrol',
            old_name='notification',
            new_name='response',
        ),
    ]
