# Generated by Django 2.1.3 on 2019-03-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20190301_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Control Categories'},
        ),
        migrations.AddField(
            model_name='entry',
            name='residual_ale_rate',
            field=models.DecimalField(decimal_places=10, default=1, help_text='Residual ALE Rate generated after Entry Overview.', max_digits=19),
        ),
    ]
