# Generated by Django 2.1.3 on 2019-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20191001_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontrol',
            name='operating_potential',
            field=models.FloatField(default=1, help_text='What pecentage is the contorol operating at based on its maximum mitigation potential'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='operating_potential_opportunity',
            field=models.TextField(blank=True, help_text='Description of addtional opportunites that could maximize the controls mitigation potential', null=True),
        ),
    ]
