# Generated by Django 2.1.3 on 2019-03-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20190301_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Control Categories'},
        ),
    ]
