# Generated by Django 2.1.3 on 2019-03-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20190306_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='residual_ale_rate',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Residual ALE Rate generated after Entry Overview.', max_digits=19),
        ),
    ]
