# Generated by Django 2.1.3 on 2018-11-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20181105_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCompanyControlCIATriad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolciatriad_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolciatriad_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolciatriad_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('id_ciatriad', models.ForeignKey(help_text='The CIA Triad', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrycompanycontrol_cia', to='risk.CIATriad')),
            ],
            options={
                'verbose_name_plural': 'Entry: Company Control CIA',
            },
        ),
        migrations.RemoveField(
            model_name='controlcategoryfunction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryfunction',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryfunction',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryfunction',
            name='id_controlcategory',
        ),
        migrations.RemoveField(
            model_name='controlcategoryfunction',
            name='id_controlfunction',
        ),
        migrations.RemoveField(
            model_name='controlcategoryfunction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrolfunction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrolfunction',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrolfunction',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrolfunction',
            name='id_controlfunction',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrolfunction',
            name='id_entrycompanycontrol',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrolfunction',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='available_function',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='functions',
        ),
        migrations.DeleteModel(
            name='ControlCategoryFunction',
        ),
        migrations.DeleteModel(
            name='ControlFunction',
        ),
        migrations.DeleteModel(
            name='EntryCompanyControlFunction',
        ),
        migrations.AddField(
            model_name='entrycompanycontrolciatriad',
            name='id_entrycompanycontrol',
            field=models.ForeignKey(help_text='The entry control the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cia_entrycompanycontrol', to='risk.EntryCompanyControl'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolciatriad',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolciatriad_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='cia_triad',
            field=models.ManyToManyField(help_text='Specifies what portion of the triad is associated to the control entry', related_name='EntryCompanyControlCIATriads', through='risk.EntryCompanyControlCIATriad', to='risk.CIATriad'),
        ),
    ]
