# Generated by Django 2.0.5 on 2018-05-29 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_auto_20180529_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmembership',
            old_name='default_company_role',
            new_name='company_role',
        ),
    ]
