# Generated by Django 2.1.3 on 2019-03-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20190306_0239'),
        ('risk', '0006_auto_20190304_1725'),
    ]

    operations = [
    ]
