# Generated by Django 2.0.5 on 2018-10-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20181024_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeunit',
            name='date_created',
        ),
    ]
