# Generated by Django 2.0.5 on 2018-05-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20180529_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User id if created by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id if deleted by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
