# Generated by Django 2.1.3 on 2018-11-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20181106_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['company']},
        ),
        migrations.RemoveIndex(
            model_name='register',
            name='risk_regist_date_mo_86830f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('name', 'company')},
        ),
    ]
