# Generated by Django 2.1.3 on 2018-12-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_auto_20181201_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email_info',
            field=models.EmailField(blank=True, help_text='Addtional information email address for the vendor.', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email_product',
            field=models.EmailField(blank=True, help_text='For internal use to get information from the vendor regarding products and services', max_length=255),
        ),
    ]
