# Generated by Django 2.1.3 on 2019-03-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_merge_20190306_0742'),
        ('risk', '0008_merge_20190306_1258'),
    ]

    operations = [
    ]
