# Generated by Django 2.1.3 on 2018-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20181202_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='url',
            field=models.URLField(blank=True, help_text='Url for the control'),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='control',
            name='model_number',
        ),
    ]
