# Generated by Django 2.0.5 on 2018-10-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_remove_timeunit_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was created', null=True),
        ),
    ]
