# Generated by Django 2.0.5 on 2018-05-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20180529_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_register',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_company',
            field=models.ForeignKey(blank=True, help_text='The default Company register that is shown first in the user portal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_company_register', to='risk.Company'),
        ),
    ]
