# Generated by Django 2.1.3 on 2018-11-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_auto_20181106_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['register', 'entry_number'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['company', 'name']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterModelOptions(
            name='timeunit',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Time Units'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='annual_rate_of_occurence',
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_fixed',
            field=models.DecimalField(decimal_places=10, default=1, help_text='Fixed number of occurrences on an annual basis to determine total frequency per year.', max_digits=19),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_frequency',
            field=models.ForeignKey(blank=True, help_text='Frequency Category used to help define ARO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_aro_frequency', to='risk.FrequencyCategory'),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_known_quantity',
            field=models.FloatField(blank=True, default=1, help_text='The number of times per ARO unit.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_toggle',
            field=models.CharField(choices=[('K', 'Known ARO'), ('C', 'Frequency Category'), ('F', 'Annualized Percentage')], default='K', help_text='Toggle to determine how the ARO is calculated', max_length=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_unit',
            field=models.ForeignKey(default=6, help_text='Cadence used on a know occurance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_aro_unit', to='risk.TimeUnit'),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='daily_units',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Number of units per day', max_digits=19),
        ),
    ]
