# Generated by Django 2.1.3 on 2018-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20181107_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='daily_units',
            field=models.DecimalField(decimal_places=8, default=1, help_text='Number of units per day', max_digits=15),
        ),
    ]
