# Generated by Django 2.0.5 on 2018-06-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20180529_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyassettype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that created the assettype', on_delete=django.db.models.deletion.PROTECT, related_name='companyassettype', to='risk.Company'),
        ),
    ]
