# Generated by Django 2.1.3 on 2019-03-12 02:08

from django.db import migrations, models
import risk.models.company


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_merge_20190306_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyartifact',
            name='artifact_file',
            field=models.FileField(null=True, upload_to=risk.models.company.get_artifact_file_path),
        ),
    ]
