# Generated by Django 2.1.3 on 2019-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_companyartifact_artifact_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetype',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
    ]
