# Generated by Django 2.0.5 on 2018-06-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20180601_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='risk_owner',
            field=models.ForeignKey(help_text=' Who owns the the information', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontact_entry', to='risk.CompanyContact'),
        ),
    ]
