# Generated by Django 2.0.5 on 2018-10-24 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_remove_timeunit_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 17, 20, 30, 255470, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
    ]
