# Generated by Django 2.1.3 on 2018-11-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20181107_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='aro_unit',
            new_name='aro_time_unit',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='aro_known_quantity',
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_known_multiplier',
            field=models.FloatField(blank=True, default=1, help_text='The number of times per time unit.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_known_unit_quantity',
            field=models.IntegerField(blank=True, default=1, help_text='Defines the number of time units chosen'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='max_year',
            field=models.TextField(blank=True, help_text='Number of years for the minimum value'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='min_year',
            field=models.TextField(blank=True, help_text='Number of years for the minimum value'),
        ),
    ]
