# Generated by Django 2.1.3 on 2018-12-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0010_auto_20181203_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='notes_mgmt',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='actorintent',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='actormotive',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='cadence',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='ciatriad',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companyassettype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrolcosttype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrolmeasure',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companylocation',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companymemberrole',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companymemberroletype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companyobjective',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companyplaybook',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companysegment',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='companyteam',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='compliancetype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='contacttype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategorytype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controlcscfamily',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controldomain',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controlfamily',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controlfunction',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='controlresponse',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='dependencyeffort',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='feedbackstatus',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='frequencycategory',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='killchain',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='mitigationadequacy',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='pyramidofpain',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='responsevote',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='severitycategory',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='usergrant',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
        migrations.AlterField(
            model_name='vendortype',
            name='bkof_notes',
            field=models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True),
        ),
    ]
