# Generated by Django 2.1.3 on 2019-04-05 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_auto_20190315_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rag',
            field=models.ForeignKey(help_text='RAG indicator of the project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_rag', to='risk.RAGIndicator'),
        ),
        migrations.AddField(
            model_name='ragindicator',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name of the color for RAG indicator', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragindicator',
            name='color_hex',
            field=models.CharField(default=django.utils.timezone.now, help_text='Hex value of the color if not defined for the RAG indicator', max_length=45),
            preserve_default=False,
        ),
    ]
