# Generated by Django 2.0.5 on 2018-06-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_entry_risk_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='risk_owner',
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_owner',
            field=models.ForeignKey(help_text=' Who owns the the information', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontact_asset', to='risk.CompanyContact'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_info',
            field=models.CharField(blank=True, help_text='Vendor information phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_support',
            field=models.CharField(blank=True, help_text='Vendor support phone number', max_length=15),
        ),
    ]
