# Generated by Django 2.1.3 on 2018-11-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_auto_20181107_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencycategory',
            name='max_year',
            field=models.CharField(blank=True, help_text='Number of years for the minimum value', max_length=128),
        ),
        migrations.AlterField(
            model_name='frequencycategory',
            name='min_year',
            field=models.CharField(blank=True, help_text='Number of years for the minimum value', max_length=128),
        ),
    ]
