# Generated by Django 2.0.5 on 2018-10-24 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_timeunit_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='account',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='actorintent',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='account',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='actormotive',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='threatactorintent',
            name='date_revoked',
        ),
        migrations.RemoveField(
            model_name='threatactorintent',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='threatactormotive',
            name='date_revoked',
        ),
        migrations.RemoveField(
            model_name='threatactormotive',
            name='revoked_by',
        ),
        migrations.AddField(
            model_name='actor',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actor_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='actor',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actor_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 43, 59, 418414, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actor',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_actor_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_actor_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='actor',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actor_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actorintent_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actorintent_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 44, 11, 314055, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actorintent',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_actorintent_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_actorintent_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actorintent_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actormotive_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actormotive_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 44, 21, 730385, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actormotive',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_actormotive_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_actormotive_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actormotive_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactorintent_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactorintent_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactorintent_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactormotive_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactormotive_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactormotive_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='actorintent',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='actorintent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='actorintent',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='actorintent',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='actormotive',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='actormotive',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='actormotive',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='actormotive',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='threatactorintent',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactorintent_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threatactorintent',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 44, 50, 625795, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threatactorintent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='threatactormotive',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactormotive_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='threatactormotive',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 19, 45, 6, 921934, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threatactormotive',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
    ]
