# Generated by Django 2.1.3 on 2018-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_auto_20181107_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencycategory',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Frequency Categories'},
        ),
        migrations.AlterModelOptions(
            name='impactcategory',
            options={'ordering': ['sort_order'], 'verbose_name_plural': 'Impact Categories'},
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='mitigation_rate',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='actor',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='companyassettype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='controlnotification',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='aro_mitigation_rate',
            field=models.FloatField(blank=True, default=0, help_text='Percentage of mitigation the control applies to the Annual Rate of Occurence'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='impact_mitigation_rate',
            field=models.FloatField(blank=True, default=0, help_text='Percentage of mitigation the control applies to the Impact'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='killchain',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='notification',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='response',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='risktype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='under_review',
            field=models.BooleanField(default=False, help_text='Designates whether this category has been marked for review'),
        ),
    ]
