# Generated by Django 2.1.3 on 2018-12-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_auto_20181203_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name_aka',
            field=models.TextField(blank=True, help_text='Other names the company may have been associated', null=True),
        ),
    ]
