# Generated by Django 2.0.5 on 2018-06-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0012_auto_20180604_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='account',
            field=models.ForeignKey(default=1, help_text='Account that the vendor is associated with.  If CORE, then all accounts', on_delete=django.db.models.deletion.PROTECT, related_name='account_vendor', to='risk.Account'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='initial_account',
            field=models.ForeignKey(default=1, help_text='Acocunt that initally created the vendor', on_delete=django.db.models.deletion.PROTECT, related_name='inital_account_vendor', to='risk.Account'),
        ),
    ]
