# Generated by Django 2.1.3 on 2019-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_auto_20190405_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='aro_fixed',
            field=models.FloatField(blank=True, default=1, help_text='Fixed number of occurrences on an annual basis to determine total frequency per year.'),
        ),
    ]
