# Generated by Django 2.0.5 on 2018-10-25 02:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_auto_20181024_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'verbose_name_plural': 'Task Status'},
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='cadence',
            name='example_title2',
        ),
        migrations.AddField(
            model_name='cadence',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_cadence_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='cadence',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_cadence_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadence',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 2, 47, 32, 376276, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadence',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='cadence',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='cadence',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='cadence',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_cadence_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadence',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_cadence_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadence',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='cadence',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='cadence',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_cadence_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_emailtemplate_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_emailtemplate_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 2, 47, 45, 997352, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_emailtemplate_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_emailtemplate_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_emailtemplate_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_taskstatus_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_taskstatus_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 2, 47, 59, 270020, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_taskstatus_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_taskstatus_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_taskstatus_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadence',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='cadence',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddIndex(
            model_name='cadence',
            index=models.Index(fields=['company'], name='risk_cadenc_company_917095_idx'),
        ),
    ]
