# Generated by Django 2.0.5 on 2018-06-04 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_auto_20180604_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User id of the user that created the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='modified_by',
            field=models.ForeignKey(default=1, help_text='User id that last modified the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
