# Generated by Django 2.1.3 on 2018-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_vendor_name_aka'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='name_aka',
            field=models.TextField(blank=True, help_text='Other names the control may have been associated', null=True),
        ),
    ]
