# Generated by Django 2.1.3 on 2018-12-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_control_name_aka'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='stock_symbol',
            field=models.CharField(blank=True, help_text='Vendor stock symbol', max_length=15, null=True),
        ),
    ]
