# Generated by Django 2.1.3 on 2018-11-12 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_auto_20181109_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='response',
            field=models.ForeignKey(blank=True, default=6, help_text='The final decsion on what to do with the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_response', to='risk.Response'),
        ),
    ]
