# Generated by Django 2.1.3 on 2019-04-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_auto_20190419_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontrol',
            name='poc_main',
            field=models.ForeignKey(blank=True, help_text='Main point of contact for items related to the control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poc_main_control', to='risk.CompanyContact'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='poc_support',
            field=models.ForeignKey(blank=True, help_text='Point of contact for support items related to the control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='poc_support_control', to='risk.CompanyContact'),
        ),
    ]
