# Generated by Django 2.0.5 on 2018-06-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_auto_20180604_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Vendor abbreviated name', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='parent',
            field=models.CharField(blank=True, help_text='Vendor parent company', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(help_text='Vendor name', max_length=255),
        ),
    ]
