# Generated by Django 2.0.5 on 2018-06-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_auto_20180604_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entry', models.ForeignKey(help_text='The entry the associated with the risk type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entryrisktype', to='risk.Entry')),
            ],
            options={
                'verbose_name_plural': 'Entry Risk Types',
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the business risk type', max_length=45)),
                ('desc', models.TextField(help_text='Description of the business risk')),
                ('keywords', models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct risk type', null=True)),
                ('example_title1', models.CharField(blank=True, help_text='Title used to support the example 1', max_length=100, null=True)),
                ('example_title2', models.CharField(blank=True, help_text='Title used to support the example 2', max_length=100, null=True)),
                ('example_content1', models.CharField(blank=True, help_text='Verbaige used to describe example 1', max_length=255, null=True)),
                ('example_content2', models.CharField(blank=True, help_text='Verbaige used to describe example 2', max_length=255, null=True)),
                ('example_image1', models.ImageField(blank=True, help_text='Image used to support context for example 1', null=True, upload_to='')),
                ('example_image2', models.ImageField(blank=True, help_text='Image used to support context for example 2', null=True, upload_to='')),
                ('desc_alt', models.CharField(blank=True, help_text='Alternate description used for image and text hover', max_length=100, null=True)),
                ('desc_form', models.CharField(blank=True, help_text='Form verbiage used for form inputs by the user', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Risk Type',
            },
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='id_risktype',
            field=models.ForeignKey(help_text='The business risk type associated with the entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risktypeentry', to='risk.RiskType'),
        ),
        migrations.AddField(
            model_name='entry',
            name='risk_types',
            field=models.ManyToManyField(help_text='Specifies business risk types are associated with the entry', related_name='EntryRiskTypes', through='risk.EntryRiskType', to='risk.RiskType'),
        ),
    ]
