# Generated by Django 2.1.3 on 2019-04-26 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_auto_20190424_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRecovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('is_test', models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_activated', models.DateTimeField(editable=False, help_text='Timestamp the field was last activated')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('recovery_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='The fixed monetary value of the recovery in dollars', max_digits=30, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the of the recovery needed if the event is triggered', null=True)),
                ('evaluation_days', models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True)),
                ('evaluation_flg', models.BooleanField(default=False, help_text='Defines if an evaluation is due for the asset')),
                ('activated_by', models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecovery_related_activated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecovery_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecovery_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecovery_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(help_text='Entry that the recovery is mapped ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryentryrecovery', to='risk.Entry')),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecovery_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entry Recovery',
            },
        ),
        migrations.CreateModel(
            name='EntryRecoveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('is_test', models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_activated', models.DateTimeField(editable=False, help_text='Timestamp the field was last activated')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the field', null=True)),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True)),
                ('abbrv', models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True)),
                ('keywords', models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True)),
                ('under_review', models.BooleanField(default=False, help_text='Designates whether this category has been marked for review')),
                ('example1', models.TextField(blank=True, help_text='Pratcial example of the category', null=True)),
                ('example2', models.TextField(blank=True, help_text='Pratcial example of the category', null=True)),
                ('activated_by', models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecoverytype_related_activated', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecoverytype_related_company', to='risk.Company')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecoverytype_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecoverytype_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecoverytype_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrecoverytype_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entry Recovery Types',
            },
        ),
        migrations.AddField(
            model_name='companyassettype',
            name='is_tangible',
            field=models.BooleanField(default=True, help_text='Designates whether asset should be considered tangible'),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='entry',
            field=models.ForeignKey(help_text='Entry that the task is mapped', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrytask', to='risk.Entry'),
        ),
        migrations.AddField(
            model_name='entryrecovery',
            name='recovery_type',
            field=models.ForeignKey(help_text='Type of asset being specified', on_delete=django.db.models.deletion.PROTECT, related_name='entryrecoverytype', to='risk.EntryRecoveryType'),
        ),
    ]
