# Generated by Django 2.0.5 on 2018-10-25 23:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_auto_20181025_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='account',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='compliance',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='compliancerequirement',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='compliancetype',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='killchain',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='pyramidofpain',
            name='example_title2',
        ),
        migrations.AddField(
            model_name='compliance',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliance_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliance_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliance',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliance_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliance_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='compliance',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliance_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancerequirement_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancerequirement_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancerequirement_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancerequirement_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancetype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancetype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancetype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancetype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancetype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_complianceversion_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 23, 57, 37, 188005, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_complianceversion_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_complianceversion_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_complianceversion_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killchain',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_killchain_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='killchain',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_killchain_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killchain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 23, 57, 46, 546723, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='killchain',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_killchain_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killchain',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_killchain_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killchain',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='killchain',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='killchain',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_killchain_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_pyramidofpain_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_pyramidofpain_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 23, 57, 54, 506591, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_pyramidofpain_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_pyramidofpain_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_pyramidofpain_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='compliancetype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='compliancetype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='compliancetype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='killchain',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='killchain',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='killchain',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='pyramidofpain',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pyramidofpain',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='pyramidofpain',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pyramidofpain',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
    ]
