# Generated by Django 2.1.3 on 2018-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0015_vendor_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='actorintent',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='actormotive',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='ciatriad',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='companyassettype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategorytype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='controldomain',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='controlfamily',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='controlfunction',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='controlresponse',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='frequencycategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='killchain',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='mitigationadequacy',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='notificationgroup',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='pyramidofpain',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='severitycategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
        migrations.AlterField(
            model_name='vendortype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True),
        ),
    ]
