# Generated by Django 2.0.5 on 2018-06-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_auto_20180605_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risktype',
            options={'verbose_name_plural': 'Risk Types'},
        ),
    ]
