# Generated by Django 2.1.3 on 2019-04-26 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_auto_20190426_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAncillary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('is_test', models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_activated', models.DateTimeField(editable=False, help_text='Timestamp the field was last activated')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('ancillary_fixed', models.DecimalField(blank=True, decimal_places=2, help_text='The fixed monetary value of the ancillary in dollars', max_digits=30, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the of the ancillary needed if the event is triggered', null=True)),
                ('evaluation_days', models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True)),
                ('evaluation_flg', models.BooleanField(default=False, help_text='Defines if an evaluation is due for the asset')),
                ('activated_by', models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillary_related_activated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entry Ancillaires',
            },
        ),
        migrations.CreateModel(
            name='EntryAncillaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('is_test', models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_activated', models.DateTimeField(editable=False, help_text='Timestamp the field was last activated')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the field', null=True)),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True)),
                ('abbrv', models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True)),
                ('keywords', models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True)),
                ('under_review', models.BooleanField(default=False, help_text='Designates whether this category has been marked for review')),
                ('example1', models.TextField(blank=True, help_text='Pratcial example of the category', null=True)),
                ('example2', models.TextField(blank=True, help_text='Pratcial example of the category', null=True)),
                ('activated_by', models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillarytype_related_activated', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillarytype_related_company', to='risk.Company')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillarytype_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillarytype_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillarytype_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillarytype_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entry Ancillary Types',
            },
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='activated_by',
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='entryrecovery',
            name='recovery_type',
        ),
        migrations.RemoveField(
            model_name='entryrecoverytype',
            name='activated_by',
        ),
        migrations.RemoveField(
            model_name='entryrecoverytype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='entryrecoverytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entryrecoverytype',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='entryrecoverytype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='entryrecoverytype',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='EntryRecovery',
        ),
        migrations.DeleteModel(
            name='EntryRecoveryType',
        ),
        migrations.AddField(
            model_name='entryancillary',
            name='ancillary_type',
            field=models.ForeignKey(help_text='Type of ancillary being specified', on_delete=django.db.models.deletion.PROTECT, related_name='entryancillarytype', to='risk.EntryAncillaryType'),
        ),
        migrations.AddField(
            model_name='entryancillary',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillary_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryancillary',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillary_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryancillary',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillary_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryancillary',
            name='entry',
            field=models.ForeignKey(help_text='Entry that the ancillary cost is mapped ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryentryancillary', to='risk.Entry'),
        ),
        migrations.AddField(
            model_name='entryancillary',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryancillary_related_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
