# Generated by Django 2.0.5 on 2018-10-26 00:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_auto_20181025_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='account',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='controlcategorytype',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='controlcscfamily',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='controlcscfamily',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='controlcscfamily',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='controlcscfamily',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='account',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='controldomain',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='controlfunction',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='controloperation',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='dependencyeffort',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='keywords',
        ),
        migrations.AddField(
            model_name='control',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_control_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='control',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_control_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 41, 17, 154864, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_control_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_control_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='control',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_control_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategory_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfunction_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 41, 24, 653881, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfunction_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfunction_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfunction_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryoperation_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 41, 31, 418552, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryoperation_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryoperation_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlcategoryoperation',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryoperation_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorytype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorytype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 41, 40, 936933, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorytype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorytype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorytype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcsc_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 41, 47, 774317, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcsc_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcsc_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcsc_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcscfamily_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcscfamily_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 41, 55, 788797, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcscfamily_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcscfamily_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcscfamily_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldomain_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldomain_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 42, 3, 700306, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controldomain',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldomain_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldomain_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldomain_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfunction_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfunction_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 42, 9, 913792, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfunction_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfunction_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfunction_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controloperation_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controloperation_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 42, 17, 746923, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controloperation',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controloperation_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controloperation_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='controloperation',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controloperation_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencyeffort_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencyeffort_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 42, 25, 506536, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencyeffort_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencyeffort_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencyeffort_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencytype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencytype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 42, 31, 528134, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencytype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencytype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='dependencytype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencytype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='control',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the control', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='control',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategory_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 42, 37, 364712, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategory_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategory_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategory_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='controlcategory',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategorytype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='controlcategorytype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='controlcategorytype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='controlcscfamily',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='controlcscfamily',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='controldomain',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='controldomain',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='controlfunction',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='controlfunction',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='controloperation',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='controloperation',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dependencyeffort',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='dependencyeffort',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dependencytype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='dependencytype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
    ]
