# Generated by Django 2.1.3 on 2019-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_auto_20190426_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryancillary',
            name='summary',
            field=models.CharField(default='summary', help_text='Brief description of the ancillary cost', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='summary',
            field=models.CharField(help_text='Brief description of the entry', max_length=600),
        ),
    ]
