# Generated by Django 2.1.3 on 2018-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_auto_20181208_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ditype',
            options={'verbose_name_plural': 'Do It Types'},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='url_product',
            new_name='url_products',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='url_service',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='url_support',
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_evaluated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the evaluation last occured', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_url_crawler',
            field=models.DateTimeField(blank=True, help_text="Timestamp the vendor url's were last crawlled", null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_about_us',
            field=models.URLField(blank=True, help_text='Vendors about us website', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_contact',
            field=models.URLField(blank=True, help_text='Vendors contact us website', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_crawler_days',
            field=models.IntegerField(blank=True, default=90, help_text='Defines the default number of days a url scan should be performed'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_crawler_flg',
            field=models.BooleanField(default=False, help_text='Defines if an url crawl is due for the vendor'),
        ),
    ]
