# Generated by Django 2.0.5 on 2018-06-05 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0017_auto_20180605_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='account',
            field=models.ForeignKey(default=1, help_text='The account that the risk type is related', on_delete=django.db.models.deletion.PROTECT, related_name='account_risktype', to='risk.Account'),
        ),
        migrations.AddField(
            model_name='risktype',
            name='results',
            field=models.TextField(blank=True, help_text='Resulting behaviour'),
        ),
    ]
