# Generated by Django 2.1.3 on 2018-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_auto_20181208_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcategory',
            name='core_expectation',
            field=models.TextField(help_text='Description of the primary purpose of the control.', null=True),
        ),
    ]
