# Generated by Django 2.0.5 on 2018-10-28 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_auto_20181026_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryResponseSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('date_presented', models.DateTimeField(blank=True, help_text='Timestamp the entry was presented for response', null=True)),
                ('date_decision', models.DateTimeField(blank=True, help_text='Timestamp the decision was made on how to handle the risk entry', null=True)),
                ('justification', models.TextField(help_text='Description of the response justification')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Budget allocated to support threat event', max_digits=30)),
                ('date_target', models.DateTimeField(auto_now_add=True, help_text='Target date to complete the response objective.  ie complete treatment date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes regarding the response decision')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponsesubmission_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponsesubmission_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponsesubmission_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entry Response Submission',
            },
        ),
        migrations.RemoveField(
            model_name='entryresponse',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entryresponse',
            name='response_votes',
        ),
        migrations.RemoveField(
            model_name='entryresponse',
            name='suggested_response',
        ),
        migrations.RenameField(
            model_name='entryevaluation',
            old_name='user',
            new_name='evaluator',
        ),
        migrations.RemoveField(
            model_name='entryactorintent',
            name='date_revoked',
        ),
        migrations.RemoveField(
            model_name='entryactorintent',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='entryactormotive',
            name='date_revoked',
        ),
        migrations.RemoveField(
            model_name='entryactormotive',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='entryindicator',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='entryresponseresult',
            name='id_entryresponse',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='mitigationadequacy',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='response',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='response',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='response',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='response',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='response',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='response',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='response',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='response',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='risktype',
            name='results',
        ),
        migrations.AddField(
            model_name='entryactor',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactor_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 29, 47, 373449, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryactor',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactor_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactor_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactor_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactorintent_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactorintent_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactorintent_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactormotive_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactormotive_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactormotive_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanyasset_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 29, 55, 650553, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanyasset_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanyasset_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanyasset_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrol_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 30, 1, 756937, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrol_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrol_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrol_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontroldependency_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 30, 9, 85929, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontroldependency_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontroldependency_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompanycontroldependency',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontroldependency_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolfunction_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 30, 16, 234066, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolfunction_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolfunction_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolfunction',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolfunction_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolmeasure_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 30, 22, 538201, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolmeasure_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolmeasure_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolmeasure_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanylocation_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 0, 270718, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanylocation_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanylocation_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanylocation_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliance_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 7, 829465, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliance_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliance_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliance_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryevaluation_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryevaluation_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryevaluation_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryevaluation_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryeventtype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 14, 908997, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryeventtype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryeventtype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryeventtype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryindicator_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 21, 548556, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryindicator_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryindicator_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryindicator_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponseresult_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 31, 118632, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponseresult_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponseresult_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponseresult_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrisktype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 38, 916389, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrisktype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrisktype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrisktype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryurl_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryurl_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_mitigationadequacy_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_mitigationadequacy_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 46, 830189, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_mitigationadequacy_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_mitigationadequacy_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_mitigationadequacy_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_response_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='response',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_response_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 31, 54, 987016, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_response_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_response_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='response',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='response',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_response_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_responsevote_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_responsevote_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 32, 1, 567926, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsevote',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_responsevote_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_responsevote_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_responsevote_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risktype',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_risktype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='risktype',
            name='context',
            field=models.TextField(blank=True, help_text='Information on how the entry is associated to the risk type'),
        ),
        migrations.AddField(
            model_name='risktype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_risktype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 32, 7, 705927, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_risktype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risktype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_risktype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risktype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='risktype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='risktype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_risktype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risktype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='vendor_control',
            field=models.ForeignKey(blank=True, help_text='The vendor control mapping the control belongs', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_companycontrol', to='risk.Control'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='aro_multiplier',
            field=models.FloatField(blank=True, default=1, help_text='Used to multiply the number of occurrences on an annual basis to determine total frequency per year.', null=True),
        ),
        migrations.AlterField(
            model_name='entryactor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactorintent_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 32, 17, 267053, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactormotive_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 32, 24, 541755, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='exposure_factor_toggle',
            field=models.CharField(choices=[('P', 'Percentage of Asset Value'), ('F', 'Fixed Impact Value')], default='P', help_text='Toggle to determine which formula is used to determine the exposure factor', max_length=1),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='entryevaluation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 32, 31, 566998, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryindicator',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='entryindicator',
            name='entry',
            field=models.ForeignKey(default=1, help_text='Entry id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryindicator_related_entry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryindicator',
            name='name',
            field=models.CharField(blank=True, help_text='Summary of the %(class)s', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryurl_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 16, 32, 38, 544945, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryurl_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='entry',
            field=models.ForeignKey(default=1, help_text='Entry id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryurl_related_entry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='name',
            field=models.CharField(blank=True, help_text='Summary of the %(class)s', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='mitigationadequacy',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='mitigationadequacy',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='responsevote',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='responsevote',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
        migrations.AlterField(
            model_name='risktype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='EntryResponse',
        ),
        migrations.AddField(
            model_name='entryresponsesubmission',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the entry impact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryresponse', to='risk.Entry'),
        ),
        migrations.AddField(
            model_name='entryresponsesubmission',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponsesubmission_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponsesubmission',
            name='response_votes',
            field=models.ManyToManyField(help_text='Shows the Decision Makers and their response', related_name='EntryResponseResult', through='risk.EntryResponseResult', to='risk.CompanyContact'),
        ),
        migrations.AddField(
            model_name='entryresponsesubmission',
            name='suggested_response',
            field=models.ForeignKey(blank=True, help_text='The suggested response on what to do with the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrysuggestedresponse', to='risk.Response'),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='id_entryresponsesubmission',
            field=models.ForeignKey(help_text='The entry associated with decisionmaker response (vote)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryresponsesubmission_decisionmaker', to='risk.EntryResponseSubmission'),
        ),
    ]
