# Generated by Django 2.0.5 on 2018-06-06 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0018_auto_20180605_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='user',
            new_name='organizer',
        ),
        migrations.AlterField(
            model_name='company',
            name='user_member',
            field=models.ManyToManyField(help_text='Specifies what users have access to the company', related_name='CompanyUserMembers', through='risk.CompanyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
