# Generated by Django 2.1.3 on 2018-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0019_controlcategory_core_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcategory',
            name='core_expectation',
            field=models.TextField(blank=True, help_text='Description of the primary purpose of the control.', null=True),
        ),
    ]
