# Generated by Django 2.0.5 on 2018-06-06 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0019_auto_20180606_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=128)),
                ('executive_summary', models.TextField(help_text='Description of the project')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the project should be treated as active')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the project was created', null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Timestamp the project was last modified', null=True)),
                ('date_start', models.DateTimeField(blank=True, help_text='Timestamp the project started', null=True)),
                ('date_close', models.DateTimeField(blank=True, help_text='Timestamp the project closed', null=True)),
                ('was_cancelled', models.BooleanField(default=False, help_text='Selection if the project was cancelled')),
                ('reason_cancelled', models.TextField(blank=True, help_text='Reason the project was cancelled')),
                ('company', models.ForeignKey(help_text='Company associated with the project ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_company', to='risk.Company')),
                ('organizer', models.ForeignKey(help_text='Organzier of the project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_organizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cadence',
            field=models.ForeignKey(help_text='Cadence of the meeting ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_cadence', to='risk.Cadence'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(help_text='Company associated with the meeting ', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_company', to='risk.Company'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(help_text='Type of meeting', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_meetingtype', to='risk.MeetingType'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(help_text='Organzier of the meeting', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
