# Generated by Django 2.0.5 on 2018-10-29 11:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_auto_20181028_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
            ],
            options={
                'verbose_name_plural': 'Project Entries',
            },
        ),
        migrations.RemoveField(
            model_name='projectentrymap',
            name='id_entry',
        ),
        migrations.RemoveField(
            model_name='projectentrymap',
            name='id_project',
        ),
        migrations.RenameField(
            model_name='projectdatechange',
            old_name='day',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='ciatriad',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='frequencycategory',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='impactcategory',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='impacttype',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='executive_summary',
        ),
        migrations.RemoveField(
            model_name='projectrisktype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='severitycategory',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='vendorcategory',
            name='example_title2',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='account',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='desc_alt',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='desc_form',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='example_content1',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='example_content2',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='example_image1',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='example_image2',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='example_title1',
        ),
        migrations.RemoveField(
            model_name='vendortype',
            name='example_title2',
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_ciatriad_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_ciatriad_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_ciatriad_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_ciatriad_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_ciatriad_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 12, 701833, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtypeciatriad_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtypeciatriad_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtypeciatriad_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtypeciatriad_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_frequencycategory_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_frequencycategory_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 25, 493775, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_frequencycategory_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_frequencycategory_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_frequencycategory_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impactcategory_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impactcategory_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 31, 103300, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_impactcategory_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_impactcategory_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impactcategory_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacttype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacttype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 39, 49118, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='impacttype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacttype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacttype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacttype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_project_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_project_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_project_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_days',
            field=models.IntegerField(blank=True, default=0, help_text='Estimated number of days to complete the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_project_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassumption',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectassumption_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassumption',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectbenefit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbenefit_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbenefit',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectbudgetchange',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbudgetchange_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudgetchange',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectdatechange',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectdatechange_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdatechange',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='completed_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that completed the milestone', on_delete=django.db.models.deletion.PROTECT, related_name='projectmilestone_usercompleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectmilestone_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisk_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisktype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisktype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='projectsuccesscriteria',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectsuccesscriteria_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsuccesscriteria',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectuat',
            name='completed_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that completed the milestone', on_delete=django.db.models.deletion.PROTECT, related_name='projectUAT_usercompleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectuat',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectuat_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectuat',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectupdate_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_severitycategory_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_severitycategory_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 44, 336650, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_severitycategory_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_severitycategory_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_severitycategory_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategory_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategory_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 50, 329235, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategory_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategory_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategory_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategorymap_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 54, 55, 836837, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategorymap_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategorymap_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategorymap_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='abbrv',
            field=models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortype_related_company', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 1, 562322, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendortype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortype_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='example1',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='example2',
            field=models.TextField(blank=True, help_text='Pratcial example of the category', null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortypemap_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 8, 974248, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortypemap_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortypemap_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Designates whether this field row has been deleted'),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortypemap_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ciatriad',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='ciatriad',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='frequencycategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='frequencycategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='impactcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_project_related_company', to='risk.Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 16, 299429, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='entries',
            field=models.ManyToManyField(help_text='Entries that are associated to the project.', related_name='ProjectEntryMaps', through='risk.ProjectEntry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectassumption_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 20, 679928, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectassumption_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectassumption_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbenefit_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 25, 923160, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbenefit_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbenefit_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbudgetchange_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 33, 65376, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbudgetchange_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbudgetchange_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectdatechange_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 38, 275493, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectdatechange_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectdatechange_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectmilestone_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 43, 476573, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectmilestone_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectmilestone_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisk_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 49, 395396, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisk_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisk_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisktype_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 55, 55, 866556, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisktype_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisktype_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectsuccesscriteria_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 56, 0, 711861, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectsuccesscriteria_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectsuccesscriteria_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectuat_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 56, 8, 781377, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectuat_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectuat_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectupdate_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectupdate_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='indicator',
            field=models.CharField(choices=[('R', 'Red'), ('A', 'Amber'), ('G', 'Green'), ('U', 'Unknown')], default='G', help_text='RAG indicator for the the current project status', max_length=1),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectupdate_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='severitycategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='severitycategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='severitycategory',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 56, 24, 226248, tzinfo=utc), editable=False, help_text='Timestamp the field was created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_deleted',
            field=models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcategorymap',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AlterField(
            model_name='vendortype',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the field', null=True),
        ),
        migrations.AlterField(
            model_name='vendortype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vendortypemap',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['company'], name='risk_projec_company_417453_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company'], name='risk_vendor_company_cbfecd_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorcategorymap',
            index=models.Index(fields=['date_modified'], name='risk_vendor_date_mo_d233a9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendortypemap',
            index=models.Index(fields=['date_modified'], name='risk_vendor_date_mo_9ef895_idx'),
        ),
        migrations.DeleteModel(
            name='ProjectEntryMap',
        ),
        migrations.AddField(
            model_name='projectentry',
            name='created_by',
            field=models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectentry_related_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectentry_related_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectentry_related_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='id_entry',
            field=models.ForeignKey(help_text='Entry that applies to the project', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entryproject', to='risk.Entry'),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='id_project',
            field=models.ForeignKey(help_text='The project associated with the entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectentry', to='risk.Project'),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectentry_related_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
