# Generated by Django 2.1.3 on 2019-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_mitigationfrequencytype_mitigationimpacttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='asset_time_unit_increment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The monetary of increment per time unite', max_digits=30),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_time_unit_quantity',
            field=models.FloatField(blank=True, help_text='Number of time units to be used for the timed based calculation', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='summary_value',
            field=models.TextField(blank=True, help_text='Summary of how the value logic was derived', null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_toggle',
            field=models.CharField(choices=[('F', 'Fixed Value'), ('P', 'Percent of Revenue'), ('TF', 'Time Based Fixed'), ('TI', 'Time Based Incremental')], default='F', help_text='Toggle to determine which formula is used to determine the assets value', max_length=1),
        ),
    ]
