# Generated by Django 2.1.3 on 2018-12-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0020_auto_20181209_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='saas',
            field=models.BooleanField(default=False, help_text='Is the control considered Software as a Service (SaaS)'),
        ),
        migrations.AddField(
            model_name='control',
            name='subscription',
            field=models.BooleanField(default=False, help_text='Is the control billed as a continous subscription'),
        ),
    ]
