# Generated by Django 2.1.3 on 2019-05-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0021_auto_20190510_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyasset',
            name='asset_timed_quantity_avaliable',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='asset_timed_quantity_relative',
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_time_unit_increment',
            field=models.FloatField(blank=True, help_text='The monetary percentage of increment per time unit', null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_fixed',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The fixed monetary value of the asset in dollars', max_digits=30),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_timed',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The monetary value of the asset per unit of time', max_digits=30),
        ),
    ]
