# Generated by Django 2.0.5 on 2018-06-07 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0021_auto_20180606_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassumption',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the assumption', on_delete=django.db.models.deletion.PROTECT, related_name='created_assumption', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_assumption', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the assumption', on_delete=django.db.models.deletion.PROTECT, related_name='modified_assumption', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='project',
            field=models.ForeignKey(help_text='Project the assumption is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_assumption', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the benefit', on_delete=django.db.models.deletion.PROTECT, related_name='created_benefit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_benefit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the benefit', on_delete=django.db.models.deletion.PROTECT, related_name='modified_benefit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='project',
            field=models.ForeignKey(help_text='Project the benefit is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_benefit', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the budget change', on_delete=django.db.models.deletion.PROTECT, related_name='created_budgetchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_budgetchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the budget change', on_delete=django.db.models.deletion.PROTECT, related_name='modified_budgetchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='project',
            field=models.ForeignKey(help_text='Project the budget change is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_budgetchange', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='risk_type',
            field=models.ForeignKey(help_text='The budget change type associated to the reason for the budget change', on_delete=django.db.models.deletion.PROTECT, related_name='risktype_budgetchange', to='risk.RiskType'),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the date change', on_delete=django.db.models.deletion.PROTECT, related_name='created_datechange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_datechange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the date change', on_delete=django.db.models.deletion.PROTECT, related_name='modified_datechange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='project',
            field=models.ForeignKey(help_text='Project the date change is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_datechange', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='risk_type',
            field=models.ForeignKey(help_text='The date change type associated to the reason for the date change', on_delete=django.db.models.deletion.PROTECT, related_name='risktype_datechange', to='risk.RiskType'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the milestone', on_delete=django.db.models.deletion.PROTECT, related_name='created_milestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_milestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the milestone', on_delete=django.db.models.deletion.PROTECT, related_name='modified_milestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(help_text='Project the milestone is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_milestone', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the risk', on_delete=django.db.models.deletion.PROTECT, related_name='created_projectrisk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_projectrisk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the risk', on_delete=django.db.models.deletion.PROTECT, related_name='modified_projectrisk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='project',
            field=models.ForeignKey(help_text='Project the risk is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_projectrisk', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='risk_type',
            field=models.ForeignKey(help_text='The risk type associated to the entry', on_delete=django.db.models.deletion.PROTECT, related_name='projectrisk_risktype', to='risk.RiskType'),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User id of the user that created the risk type', on_delete=django.db.models.deletion.PROTECT, related_name='created_projectrisktype', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_projectrisktype', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the risk type', on_delete=django.db.models.deletion.PROTECT, related_name='modified_projectrisktype', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the success criteria', on_delete=django.db.models.deletion.PROTECT, related_name='created_successcriteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_successcriteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the success criteria', on_delete=django.db.models.deletion.PROTECT, related_name='modified_successcriteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='project',
            field=models.ForeignKey(help_text='Project the success criteria is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_successcriteria', to='risk.Project'),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the UAT', on_delete=django.db.models.deletion.PROTECT, related_name='created_uat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_uat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the UAT', on_delete=django.db.models.deletion.PROTECT, related_name='modified_uat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='project',
            field=models.ForeignKey(help_text='Project the UAT is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_uat', to='risk.Project'),
        ),
    ]
