# Generated by Django 2.0.5 on 2018-10-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0021_auto_20181029_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorcategorymap',
            old_name='vendor',
            new_name='id_vendor',
        ),
        migrations.RenameField(
            model_name='vendorcategorymap',
            old_name='vendor_category',
            new_name='id_vendorcategory',
        ),
        migrations.RenameField(
            model_name='vendortypemap',
            old_name='vendor',
            new_name='id_vendor',
        ),
        migrations.RenameField(
            model_name='vendortypemap',
            old_name='vendor_type',
            new_name='id_vendortype',
        ),
    ]
