# Generated by Django 2.0.5 on 2018-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_auto_20181029_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendorcategories',
            field=models.ManyToManyField(help_text='Maps vendors to their associated category', related_name='vendorcategory_mapping', through='risk.VendorCategoryMap', to='risk.VendorCategory'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendortypes',
            field=models.ManyToManyField(help_text='Maps vendors to their associated type', related_name='vendortype_mapping', through='risk.VendorTypeMap', to='risk.VendorType'),
        ),
    ]
