# Generated by Django 2.0.5 on 2018-06-07 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_auto_20180606_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassumption',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_assumption', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the assumption', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_assumption', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_benefit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbenefit',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the benefit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_benefit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_budgetchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectbudgetchange',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the budget change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_budgetchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_datechange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectdatechange',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the date change', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_datechange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_milestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the milestone', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_milestone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_projectrisk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the risk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_projectrisk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_projectrisktype', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrisktype',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the risk type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_projectrisktype', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_successcriteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsuccesscriteria',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the success criteria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_successcriteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_uat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectuat',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User id that last modified the UAT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_uat', to=settings.AUTH_USER_MODEL),
        ),
    ]
