# Generated by Django 2.1.3 on 2019-05-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0022_auto_20190510_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='asset_value_fixed_upto',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The fixed monetary value an asset cannot exceed in dollars', max_digits=30),
        ),
    ]
