# Generated by Django 2.1.3 on 2019-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_companyasset_asset_value_fixed_upto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyasset',
            old_name='asset_time_unit_quantity',
            new_name='asset_time_unit_max',
        ),
        migrations.RenameField(
            model_name='companycontrol',
            old_name='estimated_opex',
            new_name='estimated_maint_opex',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='asset_value_timed',
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='estimated_dependency_opex',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for the control. support staff, electric, footprint, etc. (-maintenance)', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='opex_description',
            field=models.TextField(blank=True, help_text='Description of the values for operational expenditures', null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_fixed_upto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed monetary value an asset cannot exceed in dollars', max_digits=30, null=True),
        ),
    ]
