# Generated by Django 2.0.5 on 2018-06-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_auto_20180606_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the RAG indicator', max_length=45)),
                ('desc', models.TextField(help_text='Description of the RAG indicator')),
            ],
            options={
                'verbose_name_plural': 'RAG Indicators',
            },
        ),
    ]
