# Generated by Django 2.0.5 on 2018-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0023_auto_20181029_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_toggle',
            field=models.CharField(choices=[('F', 'Fixed Value'), ('P', 'Percent of Revenue'), ('T', 'Time Based Value')], default='F', help_text='Toggle to determine which formula is used to determine the assets value', max_length=1),
        ),
    ]
