# Generated by Django 2.1.3 on 2019-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_auto_20190514_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_toggle',
            field=models.CharField(choices=[('F', 'Fixed Value'), ('P', 'Percent of Revenue'), ('T', 'Time Based')], default='F', help_text='Toggle to determine which formula is used to determine the assets value', max_length=1),
        ),
        migrations.AlterField(
            model_name='entryancillary',
            name='per_occurance',
            field=models.IntegerField(default=1, help_text='Defines if an ancillary cost is based on a quantity of occurences'),
        ),
    ]
