# Generated by Django 2.0.5 on 2018-10-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_auto_20181029_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontrolopex',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companycontrolopex',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companycontrolopex',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='companycontrolopex',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='companycontrolopex',
            name='modified_by',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='aro_multiplier',
            new_name='annual_rate_of_occurence',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='avg_annual_upkeep',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='company_control_opex',
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='estimated_opex',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for the control. subscription, licensing, etc. (-dependencies)', max_digits=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='monetary_value_toggle',
            field=models.CharField(choices=[('F', 'Fixed Value'), ('P', 'Percent of Revenue')], default='F', help_text='Toggle to determine if company max loss is measured by fixed=False or par =True monetary value', max_length=1),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='exposure_factor_fixed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The fixed monetary value of the exposure factor dollars', max_digits=30),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='exposure_factor_toggle',
            field=models.CharField(choices=[('P', 'Percentage of Asset Value'), ('F', 'Fixed Impact Value')], default='F', help_text='Toggle to determine which formula is used to determine the exposure factor', max_length=1),
        ),
        migrations.DeleteModel(
            name='CompanyControlOpex',
        ),
    ]
