# Generated by Django 2.1.3 on 2018-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_auto_20181219_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontrol',
            name='centeralized',
        ),
        migrations.AlterField(
            model_name='company',
            name='monetary_value_toggle',
            field=models.CharField(choices=[('F', 'Fixed Value'), ('P', 'Percent of Revenue')], default='F', help_text='Toggle to determine if company max loss is measured by fixed=False or par=True monetary value', max_length=1),
        ),
    ]
