# Generated by Django 2.0.5 on 2018-06-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0024_ragindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this update should be treated as active')),
                ('summary', models.CharField(help_text='Summary of the update for the project', max_length=600)),
                ('desc', models.TextField(help_text='Additional detail of the update')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the update was created', null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Timestamp the update was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the update was deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the update was created', null=True)),
                ('created_by', models.ForeignKey(help_text='User id of the user that created the update', on_delete=django.db.models.deletion.PROTECT, related_name='created_projectupdate', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_projectupdate', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(help_text='Used to determine the visual indicator of the project', on_delete=django.db.models.deletion.PROTECT, related_name='project_statusindicator', to='risk.RAGIndicator')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User id that last modified the update', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_projectupdate', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project the update is associated', on_delete=django.db.models.deletion.PROTECT, related_name='project_projectupdate', to='risk.Project')),
            ],
            options={
                'verbose_name_plural': 'Project Updates',
            },
        ),
    ]
