# Generated by Django 2.0.5 on 2018-10-29 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0025_auto_20181029_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyControlContactCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('time_allocation', models.FloatField(blank=True, help_text='Annual percentage of time dedicated by the contact', null=True)),
                ('has_contingency', models.BooleanField(default=False, help_text='Designates whether there is a contingency plan in place for the dependency')),
                ('contingency_plan', models.TextField(blank=True, help_text='Defined contingency plan for the dependency', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes regarding the dependency costs', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactcost_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactcost_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactcost_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Contact Costs',
            },
        ),
        migrations.CreateModel(
            name='CompanyControlContactProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('process', models.TextField(blank=True, help_text='Summary of the process that should occur for the control to work effectively', null=True)),
                ('has_contingency', models.BooleanField(default=False, help_text='Designates whether there is a contingency plan in place for the dependency')),
                ('contingency_plan', models.TextField(blank=True, help_text='Defined contingency plan for the dependency', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes regarding the dependency', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactprocess_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactprocess_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactprocess_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Contact Processes',
            },
        ),
        migrations.CreateModel(
            name='CompanyControlTeamProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('process', models.TextField(blank=True, help_text='Summary of the process that should occur for the control to work effectively', null=True)),
                ('has_contingency', models.BooleanField(default=False, help_text='Designates whether there is a contingency plan in place for the dependency')),
                ('contingency_plan', models.TextField(blank=True, help_text='Defined contingency plan for the dependency', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes regarding the dependency', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolteamprocess_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolteamprocess_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolteamprocess_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Team Processes',
            },
        ),
        migrations.CreateModel(
            name='CompanyControlVendorCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('allocated_cost', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual allocated vendor cost to support the control.', max_digits=30)),
                ('has_contingency', models.BooleanField(default=False, help_text='Designates whether there is a contingency plan in place for the dependency')),
                ('contingency_plan', models.TextField(blank=True, help_text='Defined contingency plan for the dependency', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes regarding the dependency costs', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorcost_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorcost_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorcost_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Vendor Costs',
            },
        ),
        migrations.CreateModel(
            name='CompanyControlVendorProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('process', models.TextField(blank=True, help_text='Summary of the process that should occur for the control to work effectively', null=True)),
                ('has_contingency', models.BooleanField(default=False, help_text='Designates whether there is a contingency plan in place for the dependency')),
                ('contingency_plan', models.TextField(blank=True, help_text='Defined contingency plan for the dependency', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes regarding the dependency', null=True)),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorprocess_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorprocess_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorprocess_related_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Vendor Processes',
            },
        ),
        migrations.RemoveField(
            model_name='companycontroldependency',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companycontroldependency',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='companycontroldependency',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='companycontroldependency',
            name='id_companycontrol',
        ),
        migrations.RemoveField(
            model_name='companycontroldependency',
            name='id_controldependency',
        ),
        migrations.RemoveField(
            model_name='companycontroldependency',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='dependencytype',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontroldependency',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontroldependency',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontroldependency',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontroldependency',
            name='id_companycontroldependency',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontroldependency',
            name='id_entrycompanycontrol',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontroldependency',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual base salary of the contact', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_employee_benefits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for benefits', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_employee_tax',
            field=models.FloatField(blank=True, help_text='Corporate annual tax costs if employee', null=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_equipment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for employee equipment', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_space',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for the space to house the employee', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_training',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for training and education', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='cost_travel',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for travel', max_digits=30),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(help_text='The company that the control is related', on_delete=django.db.models.deletion.PROTECT, related_name='companycontact', to='risk.Company'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='contact_type',
            field=models.ForeignKey(help_text='The type of contact being described', on_delete=django.db.models.deletion.PROTECT, related_name='companycontacttype', to='risk.ContactType'),
        ),
        migrations.DeleteModel(
            name='CompanyControlDependency',
        ),
        migrations.DeleteModel(
            name='DependencyType',
        ),
        migrations.DeleteModel(
            name='EntryCompanyControlDependency',
        ),
        migrations.AddField(
            model_name='companycontrolvendorprocess',
            name='id_companycontrol',
            field=models.ForeignKey(help_text='The company control the dependency is associated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendorprocess_companycontrol', to='risk.CompanyControl'),
        ),
        migrations.AddField(
            model_name='companycontrolvendorprocess',
            name='id_vendor',
            field=models.ForeignKey(help_text='The vendor the company control is dependent on to function effectively', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontrol_vendorprocess', to='risk.Vendor'),
        ),
        migrations.AddField(
            model_name='companycontrolvendorprocess',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorprocess_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolvendorcost',
            name='id_companycontrol',
            field=models.ForeignKey(help_text='The company control the dependency is associated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendorcost_companycontrol', to='risk.CompanyControl'),
        ),
        migrations.AddField(
            model_name='companycontrolvendorcost',
            name='id_vendor',
            field=models.ForeignKey(help_text='The vendor the company control is dependent on to function effectively', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontrol_vendorcost', to='risk.Vendor'),
        ),
        migrations.AddField(
            model_name='companycontrolvendorcost',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorcost_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolteamprocess',
            name='id_companycontrol',
            field=models.ForeignKey(help_text='The company control the dependency is associated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teamprocess_companycontrol', to='risk.CompanyControl'),
        ),
        migrations.AddField(
            model_name='companycontrolteamprocess',
            name='id_companyteam',
            field=models.ForeignKey(help_text='The company control the dependency is associated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontrol_teamprocess', to='risk.CompanyTeam'),
        ),
        migrations.AddField(
            model_name='companycontrolteamprocess',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolteamprocess_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcontactprocess',
            name='id_companycontact',
            field=models.ForeignKey(help_text='The company contact that completes the process for the control to work effectively', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontrol_contactprocess', to='risk.CompanyContact'),
        ),
        migrations.AddField(
            model_name='companycontrolcontactprocess',
            name='id_companycontrol',
            field=models.ForeignKey(help_text='The company control the dependency is associated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactprocess_companycontrol', to='risk.CompanyControl'),
        ),
        migrations.AddField(
            model_name='companycontrolcontactprocess',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactprocess_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcontactcost',
            name='id_companycontact',
            field=models.ForeignKey(help_text='The company contact that the control depends on to work effectively', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontrol_companycontactcost', to='risk.CompanyContact'),
        ),
        migrations.AddField(
            model_name='companycontrolcontactcost',
            name='id_companycontrol',
            field=models.ForeignKey(help_text='The company contact the company control is dependent to function effectively', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontactcost_companycontrol', to='risk.CompanyControl'),
        ),
        migrations.AddField(
            model_name='companycontrolcontactcost',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactcost_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='cost_contact',
            field=models.ManyToManyField(blank=True, help_text='Staff or consultants cost required for the control to function effectively', related_name='CompanyControl_ContactCost', through='risk.CompanyControlContactCost', to='risk.CompanyContact'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='cost_vendor',
            field=models.ManyToManyField(blank=True, help_text='Vendor cost required for the control to function effectively', related_name='CompanyControl_VendorCost', through='risk.CompanyControlVendorCost', to='risk.Vendor'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='process_contact',
            field=models.ManyToManyField(blank=True, help_text='Staff or consultant processes that are required for the control to function effectively', related_name='CompanyControl_ContactProcess', through='risk.CompanyControlContactProcess', to='risk.CompanyContact'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='process_team',
            field=models.ManyToManyField(blank=True, help_text='Team processes that are required for the control to function effectively', related_name='CompanyControl_TeamProcess', through='risk.CompanyControlTeamProcess', to='risk.CompanyTeam'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='process_vendor',
            field=models.ManyToManyField(blank=True, help_text='Vendor processes that are required for the control to function effectively', related_name='CompanyControl_VendorProcess', through='risk.CompanyControlVendorProcess', to='risk.Vendor'),
        ),
    ]
