# Generated by Django 2.0.5 on 2018-07-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0025_projectupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitigationAdequacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of how adequate the mitigation is defined', max_length=45)),
                ('desc', models.TextField(help_text='Description of how adequate the mitigation is defined')),
                ('keywords', models.TextField(blank=True, help_text='Keywords used to idenify proper category or find correct field name', null=True)),
                ('example_title1', models.CharField(blank=True, help_text='Title used to support the example 1', max_length=100, null=True)),
                ('example_title2', models.CharField(blank=True, help_text='Title used to support the example 2', max_length=100, null=True)),
                ('example_content1', models.CharField(blank=True, help_text='Verbaige used to describe example 1', max_length=255, null=True)),
                ('example_content2', models.CharField(blank=True, help_text='Verbaige used to describe example 2', max_length=255, null=True)),
                ('example_image1', models.ImageField(blank=True, help_text='Image used to support context for example 1', null=True, upload_to='')),
                ('example_image2', models.ImageField(blank=True, help_text='Image used to support context for example 2', null=True, upload_to='')),
                ('desc_alt', models.CharField(blank=True, help_text='Alternate description used for image and text hover', max_length=100, null=True)),
                ('desc_form', models.CharField(blank=True, help_text='Form verbiage used for form inputs by the user', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mitigation Adequacy',
            },
        ),
        migrations.RemoveField(
            model_name='entryevaluation',
            name='evaluation_adequacy',
        ),
        migrations.DeleteModel(
            name='EvaluationAdequacy',
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='mitigation_adequacy',
            field=models.ForeignKey(help_text='Mitigation level based on infromation available', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrymitigation', to='risk.MitigationAdequacy'),
        ),
    ]
