# Generated by Django 2.0.5 on 2018-08-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0026_auto_20180730_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_company',
            field=models.ForeignKey(blank=True, help_text='The current Company register that is shown first in the user portal and user is viewing', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_company_register', to='risk.Company'),
        ),
    ]
