# Generated by Django 2.1.3 on 2018-12-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0027_auto_20181227_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyteammember',
            name='id_companycontact',
            field=models.ForeignKey(help_text='The member of the team', on_delete=django.db.models.deletion.PROTECT, related_name='companyteam_member', to='risk.CompanyContact'),
        ),
        migrations.AlterField(
            model_name='companyteammember',
            name='id_companyteam',
            field=models.ForeignKey(help_text='The company that the team is related', on_delete=django.db.models.deletion.PROTECT, related_name='member_companyteam', to='risk.CompanyTeam'),
        ),
    ]
