# Generated by Django 2.0.5 on 2018-09-06 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0027_userprofile_current_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontrol',
            name='inline_after',
            field=models.ForeignKey(blank=True, help_text='The upstream control id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_before', to='risk.CompanyControl'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='operation',
            field=models.ForeignKey(blank=True, help_text='The operation associated to the control entered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_controlentry', to='risk.ControlOperation'),
        ),
    ]
