# Generated by Django 2.1.3 on 2018-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0028_auto_20181230_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='full_name',
            field=models.CharField(default='FixMe', help_text='Full name', max_length=60),
        ),
    ]
