# Generated by Django 2.1.3 on 2018-12-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0029_companycontact_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='full_name',
        ),
    ]
