# Generated by Django 2.0.5 on 2018-09-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0029_entry_addtional_mitigation'),
        ('risk', '0027_auto_20180806_0740'),
    ]

    operations = [
    ]
