# Generated by Django 2.0.5 on 2018-09-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0030_merge_20180907_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryresponseresult',
            options={'verbose_name_plural': 'Entry Response Votes'},
        ),
        migrations.AlterModelOptions(
            name='responsevote',
            options={'verbose_name_plural': 'Response Votes'},
        ),
        migrations.RenameField(
            model_name='entryresponse',
            old_name='votes',
            new_name='response_votes',
        ),
        migrations.RemoveField(
            model_name='entryresponse',
            name='final_response',
        ),
        migrations.RemoveField(
            model_name='entryresponseresult',
            name='vote',
        ),
        migrations.AddField(
            model_name='entry',
            name='response',
            field=models.ForeignKey(blank=True, help_text='The final decsion on what to do with the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryfinalresponse', to='risk.Response'),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='vote_response',
            field=models.ForeignKey(blank=True, help_text='The suggested vote the decision maker made for the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryresponseresultvote', to='risk.Response'),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='vote_status',
            field=models.ForeignKey(default=1, help_text='The vote cast by the decision maker', on_delete=django.db.models.deletion.CASCADE, related_name='entryresponsevote', to='risk.ResponseVote'),
        ),
        migrations.AlterField(
            model_name='entryactor',
            name='id_actor',
            field=models.ForeignKey(help_text='The actor associated to the entry', on_delete=django.db.models.deletion.CASCADE, related_name='entry_actor', to='risk.Actor'),
        ),
        migrations.AlterField(
            model_name='entryactor',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry associated to the actor', on_delete=django.db.models.deletion.CASCADE, related_name='actor_entry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User id of the user that created the access', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreatedEntryActorIntent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='id_actorintent',
            field=models.ForeignKey(help_text='The intent chosen for the threat scenario', on_delete=django.db.models.deletion.CASCADE, related_name='entry_actorintent', to='risk.ActorIntent'),
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='id_entryactor',
            field=models.ForeignKey(help_text='The actor chosen for the threat scenario', on_delete=django.db.models.deletion.CASCADE, related_name='intent_entryactor', to='risk.EntryActor'),
        ),
        migrations.AlterField(
            model_name='entryactorintent',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='User id that revoked the intent from the threat actor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserRevokedEntryActorIntent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User id of the user that created the threat actor motive', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserCreatedEntryActorMotive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='id_actormotive',
            field=models.ForeignKey(help_text='The motive chosen for the threat scenario', on_delete=django.db.models.deletion.CASCADE, related_name='entry_actormotive', to='risk.ActorMotive'),
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='id_entryactor',
            field=models.ForeignKey(help_text='The actor chosen for the threat scenario', on_delete=django.db.models.deletion.CASCADE, related_name='motive_entryactor', to='risk.EntryActor'),
        ),
        migrations.AlterField(
            model_name='entryactormotive',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='User id that revoked the motive from the threat actor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserRevokedEntryActorMotive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrycause',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the cause', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrycause', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='id_companyasset',
            field=models.ForeignKey(help_text='The asset associated to the entry', on_delete=django.db.models.deletion.CASCADE, related_name='entry_companyasset', to='risk.CompanyAsset'),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry associated to the actor', on_delete=django.db.models.deletion.CASCADE, related_name='companyasset_entry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='id_companycontrol',
            field=models.ForeignKey(help_text='The company control assigned to mitigate the risk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companycontrol', to='risk.CompanyControl'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companycontrol_entry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='operation',
            field=models.ForeignKey(blank=True, help_text='The operation associated to the control entered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_controlentry', to='risk.ControlOperation'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='submitted_mitigation',
            field=models.ForeignKey(blank=True, help_text='User id of the user that last submitted mitigation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlastsubmittedmitigation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrycompanycontroldependency',
            name='id_companycontroldependency',
            field=models.ForeignKey(help_text='The dependency for the company control used on the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companycontroldependency', to='risk.CompanyControlDependency'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontroldependency',
            name='id_entrycompanycontrol',
            field=models.ForeignKey(help_text='The entry associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companycontroldependency_entry', to='risk.EntryCompanyControl'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrolfunction',
            name='id_controlfunction',
            field=models.ForeignKey(help_text='The function the control preforms against the threat event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_controlfunction', to='risk.ControlFunction'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrolfunction',
            name='id_entrycompanycontrol',
            field=models.ForeignKey(help_text='The entry control the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlfunction_entry', to='risk.EntryCompanyControl'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrolmeasure',
            name='id_companycontrolmeasure',
            field=models.ForeignKey(help_text='The measurement for the company control used on the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companycontrolmeasure', to='risk.CompanyControlMeasure'),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrolmeasure',
            name='id_entrycompanycontrol',
            field=models.ForeignKey(help_text='The entry associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companycontrolmeasure_entry', to='risk.EntryCompanyControl'),
        ),
        migrations.AlterField(
            model_name='entrycompanylocation',
            name='id_companylocation',
            field=models.ForeignKey(help_text='Company location that the risk entry applies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companylocation_entry', to='risk.CompanyLocation'),
        ),
        migrations.AlterField(
            model_name='entrycompanylocation',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with company location', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_companylocation', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entrycompliance',
            name='id_compliance',
            field=models.ForeignKey(help_text='The compliance or regulation associated with the entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrycompliance', to='risk.Compliance'),
        ),
        migrations.AlterField(
            model_name='entrycompliance',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrycompliance', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryevaluation',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the evaluation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryevaluation', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryevaluation',
            name='mitigation_adequacy',
            field=models.ForeignKey(help_text='Mitigation level based on infromation available', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrymitigation', to='risk.MitigationAdequacy'),
        ),
        migrations.AlterField(
            model_name='entryevaluation',
            name='user',
            field=models.ForeignKey(help_text='The user that performed the evaluation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryevaluation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryeventtype',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with the company control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventtype_entry', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryeventtype',
            name='id_eventtype',
            field=models.ForeignKey(help_text='Type of event associated to the threat event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_eventtype', to='risk.EventType'),
        ),
        migrations.AlterField(
            model_name='entryimpact',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the entry impact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryimpact', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryimpact',
            name='impact_type',
            field=models.ForeignKey(help_text='Impact type for the risk entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryimpact', to='risk.ImpactType'),
        ),
        migrations.AlterField(
            model_name='entryindicator',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the entry impact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryindicator', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryresponse',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the entry impact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryresponse', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryresponse',
            name='suggested_response',
            field=models.ForeignKey(blank=True, help_text='The suggested response on what to do with the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrysuggestedresponse', to='risk.Response'),
        ),
        migrations.AlterField(
            model_name='entryresponseresult',
            name='id_decisionmaker',
            field=models.ForeignKey(help_text='The decisionmaker that the risk entry response applies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisionmaker_entry', to='risk.CompanyContact'),
        ),
        migrations.AlterField(
            model_name='entryresponseresult',
            name='id_entryresponse',
            field=models.ForeignKey(help_text='The entry associated with decisionmaker response (vote)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryresponse_decisionmaker', to='risk.EntryResponse'),
        ),
        migrations.AlterField(
            model_name='entryrisktype',
            name='id_entry',
            field=models.ForeignKey(help_text='The entry the associated with the risk type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryrisktype', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryrisktype',
            name='id_risktype',
            field=models.ForeignKey(help_text='The business risk type associated with the entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risktypeentry', to='risk.RiskType'),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='closed_by',
            field=models.ForeignKey(help_text='User id of the user that created the field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closed_entrytask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_entrytask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='deleted_by',
            field=models.ForeignKey(help_text='User id if deleted by another user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_entrytask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='entry',
            field=models.ForeignKey(help_text='Entry that the registery is tied ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrytask', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='task_owner',
            field=models.ForeignKey(help_text=' Who owns the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrytask', to='risk.CompanyContact'),
        ),
        migrations.AlterField(
            model_name='entrytask',
            name='task_status',
            field=models.ForeignKey(default=1, help_text='Current status of the task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrytask_status', to='risk.TaskStatus'),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='created_by',
            field=models.ForeignKey(help_text='User id of the user that created the field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_entryurl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='deactivated_by',
            field=models.ForeignKey(help_text='User that deactivated the URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deactivated_entryurl', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the entry impact', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryurl', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryurl',
            name='recommended_by',
            field=models.ForeignKey(help_text='User that recommended the URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommended', to=settings.AUTH_USER_MODEL),
        ),
    ]
