# Generated by Django 2.1.3 on 2019-01-16 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0030_remove_companycontact_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCategoryFinePrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the field', max_length=600, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the field', null=True)),
                ('core', models.BooleanField(default=False, help_text='Is the field a core objective?')),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True)),
                ('under_review', models.BooleanField(default=False, help_text='Designates whether this category has been marked for review')),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True)),
                ('company', models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfineprint_related_company', to='risk.Company')),
                ('control_category', models.ForeignKey(help_text='The control category assigned to the information provided', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlcategory_fineprint', to='risk.ControlCategory')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfineprint_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfineprint_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfineprint_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfineprint_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Category: Fine Print',
            },
        ),
        migrations.CreateModel(
            name='ControlCategoryKPO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('summary', models.CharField(blank=True, help_text='Summary of the field', max_length=600, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the field', null=True)),
                ('core', models.BooleanField(default=False, help_text='Is the field a core objective?')),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True)),
                ('under_review', models.BooleanField(default=False, help_text='Designates whether this category has been marked for review')),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True)),
                ('company', models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorykpo_related_company', to='risk.Company')),
                ('control_category', models.ForeignKey(help_text='The control category assigned to the KPO', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlcategory_kpo', to='risk.ControlCategory')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorykpo_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorykpo_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorykpo_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorykpo_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Category: KPO',
            },
        ),
        migrations.RenameField(
            model_name='controlcategoryfeature',
            old_name='is_key',
            new_name='core',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='year_established',
            field=models.IntegerField(choices=[(1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default='1900', help_text='Year the vendor was established'),
        ),
    ]
