# Generated by Django 2.0.5 on 2018-09-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0031_auto_20180917_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_margin', models.TextField(blank=True, help_text='Brief description how the company dictates margins', null=True)),
                ('target_audience', models.TextField(blank=True, help_text='Brief description who the target audience is in the company', null=True)),
                ('value_statement', models.TextField(blank=True, help_text='Brief description how the company defines value of products/services', null=True)),
                ('culture_perception', models.TextField(blank=True, help_text='Brief description how the company culture is percieved', null=True)),
                ('number_employees', models.IntegerField(blank=True, help_text='The number of employees in the company', null=True)),
                ('number_customers', models.IntegerField(blank=True, help_text='The number of customers the company services', null=True)),
                ('historical_growth_rate', models.FloatField(blank=True, help_text='Historical Year-over-Year Growth Rate', null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='risk.Company')),
            ],
            options={
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.AlterField(
            model_name='entry',
            name='response',
            field=models.ForeignKey(blank=True, default=6, help_text='The final decsion on what to do with the threat scenario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryfinalresponse', to='risk.Response'),
        ),
    ]
