# Generated by Django 2.0.5 on 2018-09-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0032_auto_20180918_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company objective', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Description about the company objective')),
                ('monetary_value_start', models.DecimalField(decimal_places=2, default=0.0, help_text='The beginning monetary value of the objective', max_digits=30)),
                ('monetary_value_end', models.DecimalField(decimal_places=2, default=0.0, help_text='The ending monetary value of the objective', max_digits=30)),
                ('monetary_value_current', models.DecimalField(decimal_places=2, default=0.0, help_text='The ending monetary value of the objective', max_digits=30)),
                ('date_start', models.DateField(blank=True, help_text='Date the objective will start', null=True)),
                ('date_end', models.DateField(blank=True, help_text='Date the objective will end', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the objective was created', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the company objective is active.')),
                ('company', models.ForeignKey(help_text='Company id for the company has defined the objective', on_delete=django.db.models.deletion.PROTECT, related_name='companyobjective', to='risk.Company')),
                ('objective_owner', models.ForeignKey(help_text=' Who owns the requirement and detail of the objective', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companycontact_objective', to='risk.CompanyContact')),
            ],
            options={
                'verbose_name_plural': 'Company Objectives',
            },
        ),
        migrations.CreateModel(
            name='CompanyObjectiveRiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_companyobjective', models.ForeignKey(help_text='The objective the associated with the risk type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyobjectverisktype', to='risk.CompanyObjective')),
                ('id_risktype', models.ForeignKey(help_text='The business risk type associated with the objective', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risktypeobjective', to='risk.RiskType')),
            ],
            options={
                'verbose_name_plural': 'Company Objective Risk Types',
            },
        ),
        migrations.AddField(
            model_name='register',
            name='entry_number_queue',
            field=models.IntegerField(default=1, help_text='The entry number that is displayed to the contributor specific to the company register'),
        ),
        migrations.AddField(
            model_name='companyobjective',
            name='risk_types',
            field=models.ManyToManyField(help_text='Specifies business sector the objective is related', related_name='CompanyObjectiveRiskTypes', through='risk.CompanyObjectiveRiskType', to='risk.RiskType'),
        ),
    ]
