# Generated by Django 2.1.3 on 2019-01-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0032_auto_20190116_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcategorykpo',
            name='control_category',
            field=models.ForeignKey(help_text='The control category assigned to the KPO', on_delete=django.db.models.deletion.PROTECT, related_name='controlcategory_kpo', to='risk.ControlCategory'),
        ),
        migrations.AlterField(
            model_name='controlcategorysla',
            name='control_category',
            field=models.ForeignKey(help_text='The control category assigned to the information provided', on_delete=django.db.models.deletion.PROTECT, related_name='controlcategory_fineprint', to='risk.ControlCategory'),
        ),
    ]
