# Generated by Django 2.0.5 on 2018-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0033_auto_20180921_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='assumption',
            field=models.TextField(blank=True, help_text='Assumptions made when defining the entry', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='desc',
            field=models.TextField(help_text='Broader description of the registery entry'),
        ),
    ]
