# Generated by Django 2.1.3 on 2019-01-21 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0033_auto_20190116_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAlertMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the field', max_length=128, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the field', null=True)),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes.  DO NOT SHARE', null=True)),
                ('abbrv', models.CharField(blank=True, help_text='Abbreviation of the name', max_length=30, null=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, help_text='Sort order the field should be in for form selection', null=True)),
                ('keywords', models.TextField(blank=True, help_text='Keywords used to idenify or seach the field name', null=True)),
                ('under_review', models.BooleanField(default=False, help_text='Designates whether this category has been marked for review')),
                ('example1', models.TextField(blank=True, help_text='Pratcial example of the category', null=True)),
                ('example2', models.TextField(blank=True, help_text='Pratcial example of the category', null=True)),
                ('company', models.ForeignKey(default=1, help_text='Company id for the company that manages the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlalertmethod_related_company', to='risk.Company')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlalertmethod_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlalertmethod_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlalertmethod_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlalertmethod_related_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Control Alert Methods',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ControlCategoryAlertMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this field row should be treated as an active field and availiable for use by the application')),
                ('is_deleted', models.BooleanField(default=False, help_text='Designates whether this field row has been deleted')),
                ('date_created', models.DateTimeField(editable=False, help_text='Timestamp the field was created')),
                ('date_modified', models.DateTimeField(blank=True, help_text='Timestamp the field was last modified', null=True)),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the field was last deactivated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the individual was created', null=True)),
                ('description', models.TextField(help_text='Description of the how the control would operate at the selected level')),
                ('created_by', models.ForeignKey(default=13, help_text='User id of the user that created the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryalertmethod_related_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id that last deactivated the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryalertmethod_related_deactivated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id that last deleted the field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryalertmethod_related_deleted', to=settings.AUTH_USER_MODEL)),
                ('id_controlalertmethod', models.ForeignKey(help_text='Type of notification response the control provides.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alert_method_control_category', to='risk.ControlAlertMethod')),
            ],
            options={
                'verbose_name_plural': 'Control Category: Alert Methods',
            },
        ),
        migrations.RemoveField(
            model_name='controlcategoryresponse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryresponse',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryresponse',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controlcategoryresponse',
            name='id_controlcategory',
        ),
        migrations.RemoveField(
            model_name='controlcategoryresponse',
            name='id_controlresponse',
        ),
        migrations.RemoveField(
            model_name='controlcategoryresponse',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='controlresponse',
            name='company',
        ),
        migrations.RemoveField(
            model_name='controlresponse',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='controlresponse',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='controlresponse',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='controlresponse',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='controlcategory',
            name='control_response',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='response',
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='version',
            field=models.CharField(blank=True, help_text='Current version if applicable', max_length=100),
        ),
        migrations.DeleteModel(
            name='ControlCategoryResponse',
        ),
        migrations.DeleteModel(
            name='ControlResponse',
        ),
        migrations.AddField(
            model_name='controlcategoryalertmethod',
            name='id_controlcategory',
            field=models.ForeignKey(help_text='Category of control', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_control_alert_method', to='risk.ControlCategory'),
        ),
        migrations.AddField(
            model_name='controlcategoryalertmethod',
            name='modified_by',
            field=models.ForeignKey(default=13, help_text='User id that last modified the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryalertmethod_related_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='control_alert_method',
            field=models.ManyToManyField(help_text='The level at which the control category alerts to repsonder', related_name='ControlAlertMethodResponse', through='risk.ControlCategoryAlertMethod', to='risk.ControlAlertMethod'),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='alert_method',
            field=models.ForeignKey(blank=True, help_text='The notification ability associated to the control entered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertmethod_controlentry', to='risk.ControlAlertMethod'),
        ),
    ]
