# Generated by Django 2.0.5 on 2018-09-26 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0034_auto_20180926_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyControlCapex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the captial expendure', max_length=45)),
                ('detail', models.TextField(help_text='Description of the captial expendure')),
                ('date_purchased', models.DateTimeField(blank=True, help_text='Date the captial expendure was purchased', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Operational cost spent', max_digits=30)),
                ('accounting_id', models.CharField(blank=True, help_text='Id of control from the company accounting system for mapping costs', max_length=155, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this company should be treated as active')),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the deactivated the company', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the company was created', null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Timestamp the company was modified', null=True)),
                ('was_deleted', models.BooleanField(default=False, help_text='Designates whether this company should be treated as active')),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the company was created', null=True)),
                ('utility_field', models.CharField(blank=True, help_text='Backoffice field used for queries and reporting', max_length=30)),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes on company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User id if created by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_controlcapex', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_controlcapex', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id if deleted by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_controlcapex', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User id if created by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_controlcapex', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Capital Expenditures',
            },
        ),
        migrations.CreateModel(
            name='CompanyControlOpex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the operational expendure', max_length=45)),
                ('detail', models.TextField(help_text='Description of the operational expendure')),
                ('date_purchased', models.DateTimeField(blank=True, help_text='Date the operational expendure was purchased', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Operational cost spent', max_digits=30)),
                ('accounting_id', models.CharField(blank=True, help_text='Id of control from the company accounting system for mapping costs', max_length=155, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this company should be treated as active')),
                ('date_deactivated', models.DateTimeField(blank=True, help_text='Timestamp the deactivated the company', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp the company was created', null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Timestamp the company was modified', null=True)),
                ('was_deleted', models.BooleanField(default=False, help_text='Designates whether this company should be treated as active')),
                ('date_deleted', models.DateTimeField(blank=True, help_text='Timestamp the company was created', null=True)),
                ('utility_field', models.CharField(blank=True, help_text='Backoffice field used for queries and reporting', max_length=30)),
                ('bkof_notes', models.TextField(blank=True, help_text='Backoffice notes on company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User id if created by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_controlopex', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='User id if deactivated by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_controlopex', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User id if deleted by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_controlopex', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User id if created by another user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_controlopex', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Control Operational Expenditures',
            },
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='company_control_capex',
            field=models.ForeignKey(blank=True, help_text='The control captial expenditures for the company', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_control_capex', to='risk.CompanyControlCapex'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='company_control_opex',
            field=models.ForeignKey(blank=True, help_text='The control operational expenditures for the company', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_control_opex', to='risk.CompanyControlOpex'),
        ),
    ]
