# Generated by Django 2.0.5 on 2018-09-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0035_auto_20180926_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontrol',
            name='avg_annual_upkeep',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='date_maint',
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='continuous_audit',
            field=models.BooleanField(default=False, help_text='Is the company control continuously audited'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='continuous_audit_annual',
            field=models.IntegerField(default=0, help_text='Number of times a year auditing occurs'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='continuous_monitor',
            field=models.BooleanField(default=False, help_text='Is the company control continuously monitored'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='continuous_monitor_annual',
            field=models.IntegerField(default=0, help_text='Number of times a year monitoring occurs'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='est_annual_mitigation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Estimated annual mitigation against inherent risk', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='est_annual_opex',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Estimated annual cost for maintenance, licensing, consulting, etc. (-dependencies)', max_digits=30),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='centralized',
            field=models.BooleanField(default=False, help_text='Is the company control centralized or decentralized'),
        ),
    ]
