# Generated by Django 2.1.3 on 2019-01-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0035_auto_20190121_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='account_approved',
        ),
        migrations.AddField(
            model_name='account',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_account_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_accountmembership_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_accounttype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actor_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actorintent_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_actormotive_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appetite',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_appetite_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingmethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_billingmethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cadence',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_cadence_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_ciatriad_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_company_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyasset_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyassetlocation',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyassetlocation_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyassetsegment',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyassetsegment_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyassettype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyassettype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontact_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrol_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcapex',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcapex_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcontactcost',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactcost_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcontactprocess',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcontactprocess_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcost',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcost_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolcosttype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolcosttype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolfinding',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolfinding_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrollocation',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrollocation_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolmeasure',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolmeasure_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolmeasurementresult',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolmeasurementresult_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolsegment',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolsegment_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolteamprocess',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolteamprocess_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolvendorcost',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorcost_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companycontrolvendorprocess',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companycontrolvendorprocess_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyfinding',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyfinding_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companylocation_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymember',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companymember_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymembergrant',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companymembergrant_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymemberrole',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companymemberrole_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companymemberroletype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companymemberroletype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyobjective',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyobjective_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyobjectiverisktype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyobjectiverisktype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyplaybook',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyplaybook_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyplaybookaction',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyplaybookaction_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyplaybookmember',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyplaybookmember_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyplaybookmemberresponsibility',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyplaybookmemberresponsibility_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysegment',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companysegment_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyteam',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyteam_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyteammember',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_companyteammember_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliance',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliance_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancerequirement_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_compliancetype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_complianceversion_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_contacttype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='control',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_control_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlalertmethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlalertmethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlbillingmethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlbillingmethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategory_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryalertmethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryalertmethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryciatriad',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryciatriad_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorycontrol',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorycontrol_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryfeature',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfeature_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategoryfunction_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorykpo',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorykpo_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorysla',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorysla_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcategorytype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcsc_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlcscfamily_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldeliverymethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldeliverymethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controldomain_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfamily',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfamily_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfeature',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfeature_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlfunction_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlonusmethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_controlonusmethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultrolegrant',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_defaultrolegrant_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_deliverymethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_dependencyeffort_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_emailtemplate_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entry_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactor_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactorintent_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryactormotive_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycause',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycause_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanyasset_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrol_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolciatriad',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolciatriad_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanycontrolmeasure_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompanylocation_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrycompliance_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryevaluation_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryeventtype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryindicator_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponseresult_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryresponsesubmission',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryresponsesubmission_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryrisktype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrytask',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entrytask_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_entryurl_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_eventtypeciatriad_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_feedback_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_feedbackanswer_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackcorrespondence',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_feedbackcorrespondence_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_feedbackquestion_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackstatus',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_feedbackstatus_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacktype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_feedbacktype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_frequencycategory_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impactcategory_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_impacttype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_jobtitle_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killchain',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_killchain_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meeting_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meetingattendee_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingentry',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meetingentry_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtopic',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meetingtopic_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtopicaction',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meetingtopicaction_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtopiccomment',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meetingtopiccomment_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_meetingtype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_mitigationadequacy_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_notification_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationemaildistro',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_notificationemaildistro_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_notificationgroup_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onusmethod',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_onusmethod_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_project_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectassumption',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectassumption_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbenefit',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbenefit_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudgetchange',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectbudgetchange_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdatechange',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectdatechange_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectentry_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectmilestone_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisk_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectrisktype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsuccesscriteria',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectsuccesscriteria_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectuat',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectuat_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_projectupdate_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_pyramidofpain_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='register',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_register_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_response_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_responsevote_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risktype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_risktype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_severitycategory_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_taskstatus_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactorintent_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_threatactormotive_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_timeunit_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_useraccess_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergrant',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_usergrant_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_userrole_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User id that approved the vendor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendor_related_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_contact_form',
            field=models.URLField(blank=True, help_text='Vendors contact us form', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategory_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendorcategorymap_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortype_related_activated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='activated_by',
            field=models.ForeignKey(default=13, help_text='User id that last activated the field', on_delete=django.db.models.deletion.PROTECT, related_name='risk_vendortypemap_related_activated', to=settings.AUTH_USER_MODEL),
        ),
    ]
