# Generated by Django 2.1.3 on 2019-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0036_auto_20190123_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='accountmembership',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='accounttype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='actorintent',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='actormotive',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='appetite',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='billingmethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='cadence',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='ciatriad',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyasset',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyassetlocation',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyassetsegment',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyassettype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontact',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrol',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolcapex',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolcontactcost',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolcontactprocess',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolcost',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolcosttype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolfinding',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrollocation',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolmeasure',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolmeasurementresult',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolsegment',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolteamprocess',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolvendorcost',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companycontrolvendorprocess',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyfinding',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companylocation',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companymember',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companymembergrant',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companymemberrole',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companymemberroletype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyobjective',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyobjectiverisktype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyplaybook',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyplaybookaction',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyplaybookmember',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyplaybookmemberresponsibility',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companysegment',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyteam',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='companyteammember',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='compliance',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='compliancerequirement',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='compliancetype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='complianceversion',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='contacttype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlalertmethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlbillingmethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategory',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategoryalertmethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategoryciatriad',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategorycontrol',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategoryfeature',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategoryfunction',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategorykpo',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategorysla',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcategorytype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcsc',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlcscfamily',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controldeliverymethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controldomain',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlfamily',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlfeature',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlfunction',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='controlonusmethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='defaultrolegrant',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='deliverymethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='dependencyeffort',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryactor',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryactorintent',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryactormotive',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycause',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycompanyasset',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycompanycontrol',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycompanycontrolciatriad',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycompanycontrolmeasure',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycompanylocation',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entrycompliance',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryevaluation',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryeventtype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryindicator',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryresponseresult',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryresponsesubmission',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryrisktype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='entryurl',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='eventtypeciatriad',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='feedbackanswer',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='feedbackcorrespondence',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='feedbackquestion',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='feedbackstatus',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='frequencycategory',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='impactcategory',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='impacttype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='jobtitle',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='killchain',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meetingattendee',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meetingentry',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meetingtopic',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meetingtopicaction',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meetingtopiccomment',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='mitigationadequacy',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='notificationemaildistro',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='notificationgroup',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='onusmethod',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectassumption',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectbudgetchange',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectdatechange',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectentry',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectmilestone',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectrisk',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectrisktype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectsuccesscriteria',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectuat',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='projectupdate',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='pyramidofpain',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='responsevote',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='risktype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='severitycategory',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='taskstatus',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='threatactorintent',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='threatactormotive',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='timeunit',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='useraccess',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='usergrant',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='vendorcategory',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='vendorcategorymap',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='vendortype',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RenameField(
            model_name='vendortypemap',
            old_name='test_data',
            new_name='is_test',
        ),
        migrations.RemoveField(
            model_name='entrytask',
            name='test_data',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='test_data',
        ),
        migrations.RemoveField(
            model_name='feedbacktype',
            name='test_data',
        ),
        migrations.RemoveField(
            model_name='projectbenefit',
            name='test_data',
        ),
        migrations.AddField(
            model_name='account',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='actorintent',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='actormotive',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='appetite',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='billingmethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='cadence',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='ciatriad',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyassetlocation',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyassetsegment',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyassettype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolcapex',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolcontactcost',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolcontactprocess',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolcost',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolcosttype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolfinding',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrollocation',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolmeasure',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolmeasurementresult',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolsegment',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolteamprocess',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolvendorcost',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolvendorprocess',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyfinding',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companymember',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companymembergrant',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companymemberrole',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companymemberroletype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyobjective',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyobjectiverisktype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyplaybook',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyplaybookaction',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyplaybookmember',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyplaybookmemberresponsibility',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companysegment',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyteam',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='companyteammember',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='compliance',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='compliancerequirement',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='compliancetype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='complianceversion',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='contacttype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlalertmethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlbillingmethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategory',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryalertmethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryciatriad',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorycontrol',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryfeature',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategoryfunction',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorykpo',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorysla',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcategorytype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcsc',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlcscfamily',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controldeliverymethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controldomain',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlfamily',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlfeature',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlfunction',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='controlonusmethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='defaultrolegrant',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='dependencyeffort',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryactor',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryactorintent',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryactormotive',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycause',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolciatriad',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrolmeasure',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanylocation',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrycompliance',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryeventtype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryindicator',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryresponseresult',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryresponsesubmission',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entryrisktype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrytask',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='entrytask',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data'),
        ),
        migrations.AddField(
            model_name='entryurl',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='eventtypeciatriad',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedbackcorrespondence',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedbackstatus',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedbacktype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='feedbacktype',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data'),
        ),
        migrations.AddField(
            model_name='frequencycategory',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='impactcategory',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='impacttype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='killchain',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meetingentry',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meetingtopic',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meetingtopicaction',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meetingtopiccomment',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='meetingtype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='mitigationadequacy',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='notificationemaildistro',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='onusmethod',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectassumption',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectbenefit',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectbenefit',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Designates whether this field or content should be considered to be test data'),
        ),
        migrations.AddField(
            model_name='projectbudgetchange',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectdatechange',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectrisk',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectrisktype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectsuccesscriteria',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectuat',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='pyramidofpain',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='responsevote',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='risktype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='severitycategory',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='threatactorintent',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='threatactormotive',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='usergrant',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategory',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='vendorcategorymap',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='vendortype',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
        migrations.AddField(
            model_name='vendortypemap',
            name='date_activated',
            field=models.DateTimeField(blank=True, editable=False, help_text='Timestamp the field was last activated', null=True),
        ),
    ]
