# Generated by Django 2.0.5 on 2018-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0036_auto_20180926_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontrolcapex',
            name='investment_range',
            field=models.IntegerField(default=1, help_text='How long in years will the capital expenditure be invested'),
        ),
        migrations.AlterField(
            model_name='companycontrolcapex',
            name='date_purchased',
            field=models.DateTimeField(blank=True, help_text='Date the captial expenditure was purchased', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrolcapex',
            name='detail',
            field=models.TextField(help_text='Description of the captial expenditure'),
        ),
        migrations.AlterField(
            model_name='companycontrolcapex',
            name='name',
            field=models.CharField(help_text='Name of the captial expenditure', max_length=45),
        ),
        migrations.AlterField(
            model_name='companycontrolopex',
            name='date_purchased',
            field=models.DateTimeField(blank=True, help_text='Date the operational expenditure was purchased', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrolopex',
            name='detail',
            field=models.TextField(help_text='Description of the operational expenditure'),
        ),
        migrations.AlterField(
            model_name='companycontrolopex',
            name='name',
            field=models.CharField(help_text='Name of the operational expenditure', max_length=45),
        ),
    ]
