# Generated by Django 2.0.5 on 2018-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0037_auto_20180926_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrycompanyasset',
            old_name='exposure_percentage',
            new_name='exposure_factor',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='fixed_monetary_value',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='monetary_value_toggle',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='par_monetary_value',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='frequency_multiplier',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='frequency_notes',
        ),
        migrations.AddField(
            model_name='companyasset',
            name='fixed_sle_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed Single Loss Expectnacy of the asset', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='par_sle_value',
            field=models.FloatField(blank=True, help_text='The Single Loss Expectnacy the asset percentage based on the to the annual revenue', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='sle_value_toggle',
            field=models.BooleanField(default=False, help_text='Toggle to determine if company asset is measured by fixed=False or par =True sle value'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='est_refresh_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Estimated cost to preform refresh of the control', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='refresh_rate_annual',
            field=models.IntegerField(default=0, help_text='Number of years before the control must be purchased again'),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_multiplier',
            field=models.FloatField(blank=True, default=1, help_text='Used to determine the Annual Rate of Occurance or how many times the threat scenario would occur in a year', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='aro_notes',
            field=models.TextField(blank=True, help_text='Additional notes from the contributor regarding the aro calculation.'),
        ),
    ]
