# Generated by Django 2.0.5 on 2019-01-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0038_auto_20190123_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='url_contact_form',
        ),
    ]
