# Generated by Django 2.0.5 on 2018-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0038_auto_20180928_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrycompanyasset',
            old_name='exposure_factor',
            new_name='exposure_percentage',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='fixed_sle_value',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='par_sle_value',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='sle_value_toggle',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='continuous_audit',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='continuous_audit_annual',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='continuous_monitor',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='continuous_monitor_annual',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='est_annual_mitigation',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='est_annual_opex',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='est_refresh_cost',
        ),
        migrations.RemoveField(
            model_name='companycontrol',
            name='refresh_rate_annual',
        ),
        migrations.RemoveField(
            model_name='companycontrolcapex',
            name='investment_range',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='aro_multiplier',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='aro_notes',
        ),
        migrations.AddField(
            model_name='companyasset',
            name='fixed_monetary_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The fixed annual monetary value of the asset', max_digits=30),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='monetary_value_toggle',
            field=models.BooleanField(default=False, help_text='Toggle to determine if company asset is measured by fixed=False or par =True monetary value'),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='par_monetary_value',
            field=models.FloatField(blank=True, help_text='The percentage of annual revenue value of the asset', null=True),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='avg_annual_upkeep',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Annual cost for licensing, etc. (-dependencies)', max_digits=30),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='date_maint',
            field=models.DateTimeField(blank=True, help_text='Annual maintenance date', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='frequency_multiplier',
            field=models.FloatField(blank=True, default=1, help_text='Used to multiple the number of occurrences on an annual basis to determine total frequency per year.', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='frequency_notes',
            field=models.TextField(blank=True, help_text='Additional notes from the contributor regarding the frequency calculation.'),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='centralized',
            field=models.BooleanField(default=True, help_text='Is the company control centralized or decentralized'),
        ),
        migrations.AlterField(
            model_name='companycontrolcapex',
            name='date_purchased',
            field=models.DateTimeField(blank=True, help_text='Date the captial expendure was purchased', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrolcapex',
            name='detail',
            field=models.TextField(help_text='Description of the captial expendure'),
        ),
        migrations.AlterField(
            model_name='companycontrolcapex',
            name='name',
            field=models.CharField(help_text='Name of the captial expendure', max_length=45),
        ),
        migrations.AlterField(
            model_name='companycontrolopex',
            name='date_purchased',
            field=models.DateTimeField(blank=True, help_text='Date the operational expendure was purchased', null=True),
        ),
        migrations.AlterField(
            model_name='companycontrolopex',
            name='detail',
            field=models.TextField(help_text='Description of the operational expendure'),
        ),
        migrations.AlterField(
            model_name='companycontrolopex',
            name='name',
            field=models.CharField(help_text='Name of the operational expendure', max_length=45),
        ),
    ]
