# Generated by Django 2.0.5 on 2019-01-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0039_remove_vendor_url_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='url_services',
            field=models.URLField(blank=True, help_text='Vendors services website', null=True),
        ),
    ]
