# Generated by Django 2.0.5 on 2018-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0039_auto_20180928_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyasset',
            name='fixed_monetary_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed annual monetary value of the asset', max_digits=30, null=True),
        ),
    ]
