# Generated by Django 2.0.5 on 2018-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_auto_20180928_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='frequency_multiplier',
            new_name='aro_multiplier',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='frequency_notes',
            new_name='aro_notes',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='fixed_monetary_value',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='monetary_value_toggle',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='par_monetary_value',
        ),
        migrations.RemoveField(
            model_name='entrycompanyasset',
            name='exposure_percentage',
        ),
        migrations.AddField(
            model_name='companyasset',
            name='fixed_sle_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed Single Loss Expectancy of the asset', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='par_sle_value',
            field=models.FloatField(blank=True, help_text='The percentage of Single Loss Expectancy of the asset', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='sle_value_toggle',
            field=models.BooleanField(default=False, help_text='Toggle to determine if company asset is measured by fixed=False or par =True Single Loss Expectancy'),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='exposure_factor',
            field=models.FloatField(blank=True, default=1, help_text='Maximum percentage of asset value exposed given the threat scenario'),
        ),
    ]
