# Generated by Django 2.0.5 on 2019-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0040_vendor_url_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='url_solutions',
            field=models.URLField(blank=True, help_text='Vendors solutions website', null=True),
        ),
    ]
