# Generated by Django 2.0.5 on 2019-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0041_vendor_url_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='url_about_us_hash',
            field=models.CharField(blank=True, help_text='About Us url hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_about_us_http_code',
            field=models.CharField(blank=True, help_text='About Us url http code', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_contact_hash',
            field=models.CharField(blank=True, help_text='Contact url hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_contact_http_code',
            field=models.CharField(blank=True, help_text='Contact url http code', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_main_hash',
            field=models.CharField(blank=True, help_text='Main url hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_main_http_code',
            field=models.CharField(blank=True, help_text='Main url http code', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_products_hash',
            field=models.CharField(blank=True, help_text='Products url hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_products_http_code',
            field=models.CharField(blank=True, help_text='Products url http code', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_services_hash',
            field=models.CharField(blank=True, help_text='Services url hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_services_http_code',
            field=models.CharField(blank=True, help_text='Services url http code', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_solutions_hash',
            field=models.CharField(blank=True, help_text='Solutions url hash', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='url_solutions_http_code',
            field=models.CharField(blank=True, help_text='Solutions url http code', max_length=5, null=True),
        ),
    ]
