# Generated by Django 2.0.5 on 2018-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0041_auto_20180929_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='fixed_sle_quantity',
            field=models.IntegerField(default=1, help_text='The quantity of fixed_sle_value'),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='fixed_sle_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed Single Loss Expectancy of the asset in dollars', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='par_sle_value',
            field=models.FloatField(blank=True, help_text='The percentage of Single Loss Expectancy of the asset to the annual revenue', null=True),
        ),
    ]
