# Generated by Django 2.0.5 on 2018-09-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0042_auto_20180929_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyasset',
            old_name='sle_value_toggle',
            new_name='monetary_value_toggle',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='fixed_sle_quantity',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='fixed_sle_value',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='par_sle_value',
        ),
        migrations.AddField(
            model_name='companyasset',
            name='fixed_monetary_quantity',
            field=models.IntegerField(default=1, help_text='The quantity of fixed_monetary_value'),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='fixed_monetary_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The fixed monetary value of the asset in dollars', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='par_monetary_value',
            field=models.FloatField(blank=True, help_text='The percentage of monetary value of the asset to the annual revenue', null=True),
        ),
        migrations.AddField(
            model_name='companycontrolcapex',
            name='invest_range',
            field=models.IntegerField(default=1, help_text='Range in years to determine the annual investment cost of the control'),
        ),
    ]
