# Generated by Django 2.1.3 on 2019-02-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0043_auto_20190203_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='aro_mitigation_cost',
        ),
        migrations.RemoveField(
            model_name='entrycompanycontrol',
            name='impact_mitigation_cost',
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='aro_mitigation_rate',
            field=models.FloatField(blank=True, help_text='Rate of mitigation the control applies to the Annual Rate of Occurence', null=True),
        ),
        migrations.AddField(
            model_name='entrycompanycontrol',
            name='sle_mitigation_rate',
            field=models.FloatField(blank=True, help_text='Rate of mitigation the control applies to the SLE', null=True),
        ),
    ]
