# Generated by Django 2.0.5 on 2018-10-03 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0043_auto_20180929_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='addtional_mitigation',
        ),
        migrations.AddField(
            model_name='entry',
            name='date_completed',
            field=models.DateTimeField(blank=True, help_text='Timestamp the entry was completed', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Designates whether the entry is complete'),
        ),
        migrations.AddField(
            model_name='entryevaluation',
            name='approver',
            field=models.ForeignKey(help_text='The user that performed the evaluation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryevaluation_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp the entry was created', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, help_text='Timestamp the entry was deactivated', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp the entry was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='entryevaluation',
            name='entry',
            field=models.ForeignKey(help_text='The entry the associated with the evaluation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_evaluation', to='risk.Entry'),
        ),
        migrations.AlterField(
            model_name='entryevaluation',
            name='user',
            field=models.ForeignKey(help_text='The user that performed the evaluation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entryevaluation_evaluator', to=settings.AUTH_USER_MODEL),
        ),
    ]
