# Generated by Django 2.1.3 on 2019-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0044_auto_20190206_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrycompanyasset',
            old_name='exposure_factor_percent',
            new_name='exposure_factor_rate',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='impact_notes',
        ),
        migrations.AddField(
            model_name='entry',
            name='notes_mitigation',
            field=models.TextField(blank=True, help_text='Notes regarding the logic for the mitigation', null=True),
        ),
        migrations.AlterField(
            model_name='entrycompanyasset',
            name='exposure_factor_toggle',
            field=models.CharField(choices=[('R', 'Rate of Asset Value'), ('F', 'Fixed Impact Value')], default='F', help_text='Toggle to determine which formula is used to determine the exposure factor', max_length=1),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='aro_mitigation_rate',
            field=models.FloatField(blank=True, default=0, help_text='Rate of mitigation the control applies to the Annual Rate of Occurence', null=True),
        ),
        migrations.AlterField(
            model_name='entrycompanycontrol',
            name='sle_mitigation_rate',
            field=models.FloatField(blank=True, default=0, help_text='Rate of mitigation the control applies to the SLE', null=True),
        ),
    ]
