# Generated by Django 2.0.5 on 2018-10-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0044_auto_20181003_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontrol',
            name='control',
            field=models.ForeignKey(help_text='The primary control mapping for the company', on_delete=django.db.models.deletion.PROTECT, related_name='company_control', to='risk.Control'),
        ),
        migrations.AlterField(
            model_name='companycontrol',
            name='date_maint',
            field=models.DateField(blank=True, help_text='Annual maintenance date', null=True),
        ),
    ]
