# Generated by Django 2.0.5 on 2018-10-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0045_auto_20181003_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontrol',
            name='control',
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='vendor_control',
            field=models.ForeignKey(default=1, help_text='The primary control mapping for the company', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_companycontrol', to='risk.Control'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='control',
            name='account',
            field=models.ForeignKey(default=1, help_text='The account that the control is related', on_delete=django.db.models.deletion.PROTECT, related_name='account_control', to='risk.Account'),
        ),
    ]
