# Generated by Django 2.1.3 on 2019-02-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0045_auto_20190209_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='notes_mitigation',
            new_name='mitigation_notes',
        ),
    ]
