# Generated by Django 2.0.5 on 2018-10-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0047_auto_20181008_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='asset_evaluation_range',
        ),
        migrations.RemoveField(
            model_name='company',
            name='control_evaluation_range',
        ),
        migrations.RemoveField(
            model_name='company',
            name='entry_evaluation_range',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_alert',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_date_annual',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_date_asset',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_date_control',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_date_entry',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_date_individual',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_date_vendor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='evaluation_range_toggle',
        ),
        migrations.RemoveField(
            model_name='company',
            name='individual_evaluation_range',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vendor_evaluation_range',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account',
        ),
        migrations.AddField(
            model_name='company',
            name='evaluation_alert_days',
            field=models.IntegerField(default=14, help_text='Range in days that an alert should be sent the evaluation is due'),
        ),
        migrations.AddField(
            model_name='company',
            name='evaluation_days',
            field=models.IntegerField(default=365, help_text='Defines the default number of days an evaluation should occur'),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='evaluation_days',
            field=models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='evaluation_flg',
            field=models.BooleanField(default=False, help_text='Defines if an evaluation is due for the asset'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='evaluation_days',
            field=models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='evaluation_flg',
            field=models.BooleanField(default=False, help_text='Defines if an evaluation is due for the asset'),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='evaluation_days',
            field=models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True),
        ),
        migrations.AddField(
            model_name='companycontrol',
            name='evaluation_flg',
            field=models.BooleanField(default=False, help_text='Defines if an evaluation is due for the control'),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='evaluation_days',
            field=models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True),
        ),
        migrations.AddField(
            model_name='companylocation',
            name='evaluation_flg',
            field=models.BooleanField(default=False, help_text='Defines if an evaluation is due for the asset'),
        ),
        migrations.AddField(
            model_name='entry',
            name='evaluation_days',
            field=models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='evaluation_flg',
            field=models.BooleanField(default=False, help_text='Defines if an evaluation is due for the asset'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_approved',
            field=models.BooleanField(default=False, help_text='Defines if a company vendor can be used at the account level'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company that the vendor is associated with.  If CORE, then all accounts and companies', on_delete=django.db.models.deletion.PROTECT, related_name='company_vendor', to='risk.Company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='evaluation_days',
            field=models.IntegerField(blank=True, help_text='Defines the default number of days an evaluation should occur', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='evaluation_flg',
            field=models.BooleanField(default=False, help_text='Defines if an evaluation is due for the vendor'),
        ),
    ]
