# Generated by Django 2.0.5 on 2018-10-13 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0048_auto_20181010_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyasset',
            old_name='fixed_monetary_quantity',
            new_name='asset_quantity_fixed',
        ),
        migrations.RenameField(
            model_name='companyasset',
            old_name='fixed_monetary_value',
            new_name='asset_value_fixed',
        ),
        migrations.RenameField(
            model_name='companyasset',
            old_name='par_monetary_value',
            new_name='asset_value_par',
        ),
        migrations.RenameField(
            model_name='entrycompanyasset',
            old_name='fixed_exposure_factor_value',
            new_name='exposure_factor_fixed',
        ),
        migrations.RenameField(
            model_name='entrycompanyasset',
            old_name='asset_exposure_factor_value',
            new_name='exposure_factor_percent',
        ),
        migrations.RemoveField(
            model_name='companyasset',
            name='monetary_value_toggle',
        ),
        migrations.RemoveField(
            model_name='entrycompanyasset',
            name='asset_exposure_factor_toggle',
        ),
        migrations.RemoveField(
            model_name='entrycompanyasset',
            name='timed_exposure_factor_default',
        ),
        migrations.RemoveField(
            model_name='entrycompanyasset',
            name='timed_exposure_factor_unit',
        ),
        migrations.RemoveField(
            model_name='entrycompanyasset',
            name='timed_exposure_factor_value',
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_timed_quantity_avaliable',
            field=models.FloatField(blank=True, help_text='Default number of units used for calucalting the exposure factor', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_timed_quantity_relative',
            field=models.FloatField(blank=True, help_text='Default number of units used for calucalting the exposure factor', null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_timed_unit',
            field=models.ForeignKey(default=3, help_text='Time units used to determine the value of the asset', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companyassetunits', to='risk.TimeUnit'),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_value_timed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The monetary value of the exposure factor per unit in dollars', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='asset_value_toggle',
            field=models.IntegerField(choices=[(1, 'Fixed Value'), (2, 'Percent of Revenue'), (3, 'Time Based Value')], default=1, help_text='Toggle to determine which formula is used to determine the assets value'),
        ),
        migrations.AddField(
            model_name='entrycompanyasset',
            name='exposure_factor_toggle',
            field=models.IntegerField(choices=[(1, 'Percentage of Asset Value'), (2, 'Fixed Impact Value')], default=1, help_text='Toggle to determine which formula is used to determine the exposure factor'),
        ),
    ]
