# Generated by Django 2.0.5 on 2018-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0049_auto_20181013_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryimpact',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entryimpact',
            name='impact_type',
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_timed_quantity_avaliable',
            field=models.FloatField(blank=True, help_text='The amount of time units avaiable annually', null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_timed_quantity_relative',
            field=models.FloatField(blank=True, help_text='Number of time units to be used from the avaliable pool', null=True),
        ),
        migrations.AlterField(
            model_name='companyasset',
            name='asset_value_timed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The monetary value of the asset per unit of time', max_digits=30, null=True),
        ),
        migrations.DeleteModel(
            name='EntryImpact',
        ),
    ]
