# Generated by Django 2.0.5 on 2018-10-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0050_auto_20181014_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frequency',
            new_name='FrequencyCategory',
        ),
        migrations.RenameModel(
            old_name='Impact',
            new_name='ImpactCategory',
        ),
        migrations.AlterModelOptions(
            name='frequencycategory',
            options={'verbose_name_plural': 'Frequency Categories'},
        ),
        migrations.AlterModelOptions(
            name='impactcategory',
            options={'verbose_name_plural': 'Impact Categories'},
        ),
    ]
