# Generated by Django 2.0.5 on 2018-10-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0051_auto_20181014_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Severity',
            new_name='SeverityCategory',
        ),
        migrations.AlterModelOptions(
            name='severitycategory',
            options={'verbose_name_plural': 'Severity Categories'},
        ),
    ]
