# Generated by Django 2.0.5 on 2018-10-17 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0053_auto_20181017_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role of the member', max_length=128)),
                ('desc', models.TextField(blank=True, help_text='Description of the role')),
                ('keywords', models.TextField(blank=True, help_text='Words used to search the role')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the role is active for use')),
                ('company', models.ForeignKey(default=1, help_text='The company that the member role is related', on_delete=django.db.models.deletion.PROTECT, related_name='company_memberrole', to='risk.Company')),
            ],
            options={
                'verbose_name_plural': 'Company Member Roles',
            },
        ),
        migrations.RemoveField(
            model_name='companymemmberrole',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companymemmberrole',
            name='companymemberroletype',
        ),
        migrations.RemoveField(
            model_name='companymemberroletype',
            name='abbrv',
        ),
        migrations.AlterField(
            model_name='companymemberroletype',
            name='desc',
            field=models.TextField(blank=True, help_text='Description of the company role type', null=True),
        ),
        migrations.DeleteModel(
            name='CompanyMemmberRole',
        ),
        migrations.AddField(
            model_name='companymemberrole',
            name='company_member_role_type',
            field=models.ForeignKey(blank=True, help_text='The role type that the member role is related', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_memberroletype', to='risk.CompanyMemberRoleType'),
        ),
    ]
