# Generated by Django 2.0.5 on 2018-10-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0055_auto_20181017_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymemberrole',
            old_name='desc',
            new_name='description',
        ),
    ]
